src/dom-wrapper.ts
src/vue-wrapper.ts
tests/emit.spec.ts
tests/get.spec.ts

As it looks like the `get` method was not yet implemented, but was planned to, here is a little PR that adds it (I have so many tests that use it, it would make my life easier to test-drive this enw release 🙂 ).
I implemented the same logic it has in VTU v1.0, feedback welcome.

feat: get method on wrapper

---

src/vue-wrapper.ts
tests/vm.spec.ts

It currently returns the vm of the parent element.
With this commit, it now returns the vm of the tested element.
The test showcases the correct behavior: you can reproduce the issue by adding the test to the master banch. It will fail as it returns the vm of the parent which has no msg, isEnabled fields and toggle function.

fix: vm should be the vm of the tested component

---

src/mount.ts
src/vue-wrapper.ts
tests/vm.spec.ts

This is on top of #64 
The types have been tweaked to avoid the need of casting like `(wrapper.vm as any).msg`.
The test showcases the correct behavior: you can reproduce the issue by adding the test to the master banch. It will:
- not compile without a `as any` cast
- fail as it returns the vm of the parent which has no `msg`, `isEnabled` fields and `toggle` function.

fix: vm should be properly typed

---

src/vue-wrapper.ts
tests/props.spec.ts

Mostly useful for the upcoming `stubs` and `findComponent` implementations.

Add props accessor method

---

.github/workflows/ci.yml
package.json
test-dts/index.d-test.ts
yarn.lock

This adds a new Ci task to check that the typings are as expected. It uses `tsd` (as done on `vue-next`), and adds a basic test in `test-dts`for the wrapper inference.
Note that I had to to @types/node to avoid an issue I fixed in Vue itself https://github.com/vuejs/vue-next/pull/968
This is a base PR for a follow-up that will improve the typings of `mount` and `props` options as @lmiller1990 suggested

chore: add tsd tests for typings

---

.github/workflows/ci.yml
package.json
src/mount.ts
test-dts/index.d-test.ts
yarn.lock

This improves the signature of `mount` in order to have a proper type checking of `vm`.
On top of #72

fix: improve vm types

---

docs/API.md
src/constants.ts
src/emitMixin.ts
src/error-wrapper.ts
src/mount.ts
src/types.ts
src/utils/find.ts
src/utils/matchName.ts
src/vue-wrapper.ts
tests/find.spec.ts
tests/findAllComponents.spec.ts
tests/findComponent.spec.ts
tests/setProps.spec.ts
tests/vm.spec.ts
yarn.lock

This PR allows finding a Vue Component and returning a new VueWrapper with it's instance.
* Returns only Vue components, and works only on VueWrapper. 
* You cant chain it from a DOMWrapper 
* setProps does not work on newly wrapped instances, from FindComponent. (which is fine)
Many codebases use Components, Ref or Name  to search for Vue instances, when doing tricky assertions, or mounting shallow.

Find by component

---

docs/API.md

The examples still metnion `find` whereas it should be  `findComponent`

fix: findComponent in docs

---

README.md
src/error-wrapper.ts
src/mount.ts
src/vue-wrapper.ts
tests/findComponent.spec.ts
tests/lifecycle.spec.ts

add `unmount` to the wrapper
Named `unmount` to be inline with vue3
Not throwing exception when you `unmount` multi times, because vue3 only warns 
https://github.com/vuejs/vue-next/blob/a51b05267231fb1770d6fc727bc276475c21d27f/packages/runtime-core/src/apiCreateApp.ts#L233-L239

feat: add unmount to wrapper

---

src/mount.ts
test-dts/index.d-test.ts

This offers proper typings for the props given in the mounting options.
For example `mount(defineComponent({ props: { a: string}}), {props: {a: 2}})` fails to compile.
Only issue with this PR is that we need `ExtractPropTypes` to be public to properly type check the case `mount({ props: { a: String }}, { props: {a: 2}})`.
I'll open a discussion on vue-next and link back here (see https://github.com/vuejs/vue-next/pull/983).
Update: Evan merged it, so we'll be able to merge this one when beta.2 is released.
On top of #73

feat: properly type mount with props

---

src/utils.ts

Fixes something I spotted after #53 was merged
`globalProperties` is not supported AFAIK and was removed from the original PR except in the `mergeGlobalProperties` utils.
With the various parameters correctly typed, the code was throwing a compilation error as TS can spot that `globalProperties` is not a key of `GlobalMountOptions`.

fix: remove globalProperties

---

src/emitMixin.ts
tests/emit.spec.ts

This commit fixes an issue where emit is replaced but does not does its job, so a component emitting an event never really emits it, and a parent component never receives it.
The unit test added reproduces the issue.

fix: emit should propagate the event

---

package.json
rollup.config.js
src/create-dom-event.ts
src/utils.ts
yarn.lock

Now generates an iife build, that you can use (assumes `Vue` and `_` are globally available).
I tested it like this
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title></title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.15/lodash.js"></script>
<script>
</script>
<script src="./vue.global.js"></script>
<script src="./dist/vue-test-utils.browser.js"></script>
</head>
<body>
</body>
</html>
```
And I was able to access `VueTestUtils` globally and do some basic stuff.
I am still learning rollup, so this config can probably be improved as we go. I will add some e2e tests for this soon, too.

Improve build step, support iife build for browser usage

---

src/config.ts
src/index.ts
src/vue-wrapper.ts
tests/features/plugins.spec.ts

This is just an example how one can extend VTU with either normal prototype attachment, or via a dedicated API.
Please give me your opinions on which one you think is better?

POC extending without plugin

---

src/vue-wrapper.ts
test-dts/getComponent.d-test.ts
tests/get.spec.ts
tests/getComponent.spec.ts

This introduces a `getComponent` which returns a `VueWrapper` or throws.
It offers two benefits:
- a symetric API for components/elements with `findComponent/findAllComponents/getComponent`/`find/findAll/get`
- a better experience for TS users (as `findComponent` returns a union type, you can't chain certain things until you disambiguated the type manually).
I also refactored the signatures of `find` to offer proper overloads (the current version breaks tests compilation in a real app, i hope this fixes it). I added TSD tests to ensure the inference is working properly.

feat: getComponent

---

README.md
tests/mountingOptions/props.spec.ts

This is pretty self explanatory but I wanted to make sure it works.

feat: Explain how to replace attrs with props

---

src/vue-wrapper.ts
tests/getComponent.spec.ts

As the selector can have different shapes, this improve the error message to be more friendly.

fix: improve error message for getComponent

---

src/dom-wrapper.ts
src/error-wrapper.ts
src/index.ts
src/stubs.ts
src/types.ts
src/vue-wrapper.ts
tests/features/plugins.spec.ts
tests/find.spec.ts
tests/utils.ts

Greatly simplify the concept of `ErrorWrapper` and eliminate the need for the `WrapperAPI` interfaces (since they are not implemented by more than one class).
It's everyone favorite kind of PR - one that has more deletions than insertions!
#91  and #92

refactor: eliminate need for error wrapper class

---

src/stubs.ts

A more correct type would be:
```ts
type VNodeArgs = Parameters<Parameters<typeof transformVNodeArgs>[0]>[0]
```
But it's a bit harder to read

types: Assign the correct typing for vnodes

---

README.md
src/mount.ts
src/vue-shims.d.ts
test-dts/mount.d-test.ts
tests/mountingOptions/attrs.spec.ts
tests/mountingOptions/props.spec.ts

This allows a slightly better type checking, even if `defineComponent({ props: { a: String }})` sadly has `$props` typed as `{ a: string } & VNodeProps` and `VNodeProps` allows anything. I'm not sure we can do much on VTU side for now.
See https://github.com/vuejs/vue-test-utils-next/pull/90 for context

feat: split attrs and props mounting options

---

src/mount.ts
tests/mountingOptions/attachTo.spec.ts

As `attachTo` can be a CSS selector, if the provided selector can not be found by `document.querySelector` than an obscure error is thrown `Cannot read property 'appendChild' of null`. This handles such a case to throw a more intuitive error.
Unable to find the element matching the selector #unknown given as the `attachTo` option

fix(mount): throws if unknown attachTo

---

src/index.ts
src/mount.ts
src/stubs.ts
tests/components/ComponentWithChildren.vue
tests/components/WithProps.vue
tests/shallowMount.spec.ts

Adds a basic implementation for `shallowMount` via `MountOptions.shallow`
I still need to add tests, but it seems to work great.
resolves #6

feat: shallow mount

---

src/config.ts
src/stubs.ts
tests/components/ComponentWithSlots.vue
tests/mountingOptions/stubs.global.spec.ts

This is what I got... and I am not sure I like it...
1. Scoped slots just cannot work with auto stubs and `shallowMount`.
1. We cannot know what slots a component has defined, we can just render everything.
Check it out, play with it if you want. I wanted Evan to give me an advice on this, but yeah...
Related to #69

POC - Render all stub slots via config 

---

rollup.config.js
src/mount.ts
src/utils/compileSlots.ts
tests/components/ComponentWithSlots.vue
tests/mountingOptions/slots.spec.ts

This PR implements the previously very convenient scoped slot syntax of providing just a template string.

Feat: Implement Scoped Slot string support

---

src/mount.ts

This PR addresses the second error in #61:
```
error  in /Users/ced-pro/Code/vtu-next-test/node_modules/@vue/test-utils/dist/mount.d.ts
ERROR in /Users/ced-pro/Code/vtu-next-test/node_modules/@vue/test-utils/dist/mount.d.ts(9,9):
9:9 Property 'default' of type 'string | VNode<RendererNode, RendererElement> | { render: Function; } | undefined' is not assignable to string index type 'Slot'.
7 |     props?: Record<string, any>;
8 |     slots?: {
>  9 |         default?: Slot;
|         ^
10 |         [key: string]: Slot;
11 |     };
12 |     global?: {
```
From [this SO thread](https://stackoverflow.com/a/45261035/3366431):
> TypeScript interfaces do not have an "`additionalProperties`" mechanism like JSON Schema does.
Here's a minimal reproduction in TypeScript to help illustrate the …

fix: add slot dictionary type as typescript string index assignment workaround

---

package.json
rollup.config.js
src/create-dom-event.ts
src/mount.ts
src/utils.ts
tests/config.spec.ts
tests/shallowMount.spec.ts
yarn.lock

As pointed about by @JessicaSachs, our es build was depending on cjs dependencies.
Although I like the idea of only shipping our code and asking the users to install dependencies like lodash, it does add a bit of complexity. Eg, depending if you are using VTU in a browser/node/es build, you need to include dependencies differently.
In this PR, we now inline some dependencies:
- `lodash/isString`, `lodash/mergeWith`
- `eventTypes` (for `trigger`)
Vue and compiler-sfc and compiler-dom are still peer dependencies, so the user will bring their own version of those.
This does increase the bundle size - from 900 lines to around 4000. That said, mostly you will not be shipping this library to users, and 4000 lines is before minify, so it could be smaller, if the user wants to make it smaller, so …

fix: bundle dependencies inline and fix es build

---

src/mount.ts
tests/functionalComponents.spec.ts

This PR allows mounting and testing functional components.
I think we should add a test for a few more things, like setProps etc. 
Also `setData` makes no sense in a FunctionalComponent, for obv reasons.
`vm` is not the functional component, because there is no instance there.

fix: allow mounting functional components

---

src/mount.ts

Running `yarn test` on master fails by TS compilation errors. 🤔 
Fixed, not sure how this got introduced.

types: fix typing for options.attachTo

---

src/stubs.ts
src/utils/matchName.ts
src/utils/vueShared.ts
src/vue-wrapper.ts

Currently @vue/shared is an internal library that doesn't support browser usage. We only depend on it for some string utility functions and the ShapeFlag type.
We will revisit if @vue/shared will eventually ship a dist'd es build that is browser compatible. Until then, this will make Vue Test Utils ES compatible

fix: esm build support by inlining @vue/shared utility functions

---

src/mount.ts
src/types.ts

This commit tidies up the types in mount. The goal is to enable `strict: true` in the future on the project, and this commit fixes up a bunch of errors that the strict mode complains about.
The only change for VTU users is that `GlobalMountOptions.config` now does not allow to override `isNativeTag` as it is private and readonly in `AppConfig`: https://github.com/vuejs/vue-next/blob/71a942b25a2cad61c3d670075523c31d296c7089/packages/runtime-core/src/apiCreateApp.ts#L46-L48

chore: typings maintenance in mount

---

src/mount.ts
test-dts/shallowMount.d-test.ts

`shallowMount` now has the same signatures than `mount`, to which it delegates the heavy work.

chore: shallowMount overloads

---

src/dom-wrapper.ts
src/vue-wrapper.ts
test-dts/wrapper.d-test.ts

This provides a better type checking than the optional parameter.
ping @JessicaSachs as we talked about that on Discord: if you want to take a quick look, my explanation will probably make more sense with the proper code :)

chore: wrapper overloads signatures

---

src/create-dom-event.ts
tests/trigger.spec.ts

This PR fixes an issue with Vue 3 handling modifiers and keyCodes.
It should now allow passing modifiers the same way as you would do with in Vue. Main fixes are general key modifiers and system key modifiers.
* `trigger('keydown.meta.shift.c')` - will trigger a `cmd` + `shift` + `c` event listener.
* `trigger('keydown.13')` - will trigger on `enter` only, because keyCode is no longer supported.
* `trigger('click.right')` - will trigger a righclick `contextmenu` event. 
* `trigger('click.middle')` - will trigger a middle click event. 
While writing the docs for form handling I asked myself if we support `trigger('keydown.enter')` syntax, as I am sure we do in VTU 1, hence we have a dedicated test even - https://github.com/vuejs/vue-test-utils/blob/dev/test/specs/wrapper/trigger.spec.js#L73 …

Fix: trigger not working with some dot.notation modifiers

---

src/config.ts
tests/features/plugins.spec.ts

Adds typings to plugins, still in the quest for switching the TS config to `strict`

chore(config): proper typings for plugins

---

src/utils.ts

Adds typings to utils, still in the quest for switching the TS config to `strict`
Also removes the apparently unused utils method `isString`

chore(utils): proper typings

---

src/emitMixin.ts

Adds typings to `emitMixin`, still in the quest for switching the TS config to `strict`

chore(emitMixin): proper typings

---

src/utils/find.ts

Adds some typings to the find functions, and handle a case surfaced by TS (but that I did not manage to reproduce via unit tests, so it might never happen).

chore(find): proper typings

---

package.json

If I'm not mistaken, `@vue/compiler-sfc` is never used in this codebase.
It seems to be a peer dependency of vue-jest v5 (but somehow not explicitly specified).
But as this library is framework agnostic, the peer dependency of `vue-jest` should not imply a peer dependency of the library. For users who don't need to test `.vue` files, `@vue/compiler-sfc` is extraneous.

chore: @vue/compiler-sfc is not a peer dependency

---

src/mount.ts
test-dts/mount.d-test.ts

This improves typing when using 
```ts
mount({
props: {
// ...
}
})
```
and also adds the data type validation
```ts
const AppWithDefine = defineComponent({
props: {
a: {
type: String,
required: true
},
b: Number
},
template: ''
})
// no data provided
expectError(
mount(AppWithDefine, {
data() {
return {
myVal: 1
}
}
})
)
```

feat: improve mount typings when using object syntax and infer Data type

---

README.md

- adjust duplicate fragment of sentence
- removed empty spaces

chore: adjust duplicate sentence part in README.md

---

src/dataMixin.ts
src/stubs.ts

chore(stubs): proper typings

---

package.json
src/stubs.ts
tests/shallowMount.spec.ts
yarn.lock

I was trying to update VTU 2.x from Vue beta.15 to beta.16 (beta.17 is the same), and we are having some regressions.
It looks like an SFC with just a template tag was passed to `transformVNodeArgs` as:
`{ render: [Function: render], name: 'component-without-name' }`
and now is passed as:
`{ render: [Function: render] }`
As we need the name for stubbing/shallow mount, we have test failures.

repro: beta.16 regressions

---

src/stubs.ts
src/utils/find.ts
src/utils/matchName.ts

Instead of always patching the missing name with the registration name, we now look into the parent registration only if the name is missing.
Some cases were trickier to handle (for example when we try to find a component that has been stubbed), but it looks like we are on par with what we had previously and we do not have the risk of multiple registration names erasing each other anymore.

refactor: properly find/stub anonymous component

---

tests/shallowMount.spec.ts

Some shallow mount tests were ignored.

fix: remove only in tests

---

src/mount.ts

remove Useless code
because https://github.com/vuejs/vue-next/pull/1361 is merged

chore: remove ComponentOptionsMixin

---

package.json
src/utils/find.ts
test-dts/mount.d-test.ts
test-dts/shallowMount.d-test.ts
tests/features/async-components.spec.ts
tests/mountingOptions/props.spec.ts
yarn.lock

Each commit explains the reasoning behind the changes, but TL;DR: we had some compilation issue easy to fix, and a small refactor to do after the component resolution changes that Evan did in rc.5.

fix: find component after rc.5 refactor (and other minor fixes)

---

src/utils/find.ts
tests/find.spec.ts
tests/findComponent.spec.ts

Slightly updates the find implementation to:
- check the suspense `subtree` if it is resolved
- check the suspense `fallbackTree` otherwise
A test has been added to check if we can find a component in both cases.

feat: findComponent can find component inside a Suspense

---

src/vueWrapper.ts

Refers to [this](https://github.com/vuejs/vue-test-utils-next/issues/176)
This MR suggests to improve the guideline that `get()` should (and cannot) be used in combination with `exists()` by removing it from its return type.
The following changes only affect TS users as they will now see an error when using `exists()` on the returned `get()` result (it's assumed that when `get()` cannot find an element, it will just throw). They will need to update the code to use `find()` which is [the official recommendation](https://github.com/vuejs/vue-test-utils-next-docs/pull/48).

fix: make get() return type adhering to its return type

---

package.json
src/emitMixin.ts
yarn.lock

Hacky but fixes #197 
Investigating why `config.warnHandler` does not work...

fix: swallow warning for emitted events and bump to rc10

---

src/mount.ts
src/utils/compileSlots.ts
tests/mountingOptions/slots.spec.ts

fix: trim slot when passed a string

---

src/mount.ts
test-dts/mount.d-test.ts
tests/mountingOptions/props.spec.ts

- Adds support for mounting with `propsData` option,
for backwards compatibility.
See https://github.com/vuejs/vue-test-utils-next/issues/204
Added two tests to be clear what happens when both `props` and `propsData` are provided. Happy to change implementation to a different behaviour if that would be preferred. 
(No warning/error is given to the user if both `props` and `propsData` are used in the mounting options.)

feat(mount): add support for propsData

---

package.json
src/utils/find.ts
yarn.lock

https://github.com/vuejs/vue-next/pull/2099 introduced a big refactoring in how Suspense works, which broke VTU.
`SuspenseBoundary` no longer exposes the same interface, so our current implementation was not compiling anymore (and throwing at runtime).
This solves the issue and simplifies the current code, as the newly introduced `activeBranch` field now contains the... active branch of the Suspense, so we just have to check that.

fix: findComponent in Suspense for rc.11

---

src/config.ts
src/domWrapper.ts
src/mount.ts
src/stubs.ts
src/types.ts
src/utils/isElementVisible.ts
tests/isVisible.spec.ts
tests/mountingOptions/stubs.global.spec.ts

resolves #210 
- Add `isVisible` back. We decided to un-deprecate it in V1, porting it to V2.
- We stub transition and transition group by default in V1. We will do the same here for consistency.
- This solves the problem in #210 (see there for more context)
- Stubbing transitions avoids the problem where transitions take time (eg 0.25s) and your assertion runs before your transition has finished. In unit tests you don't really care about things like CSS transitions; you just care if things are visible or not via `v-show`.
- You can opt out on a test-by-test basis by passing `transition: false` and `transition-group: false` to `global.stubs`.
- you can opt out globally by doing `config.global.stubs = { transition: false }`. This is useful for libraries like …

Add isVisible and stub transition/transition-group by default

---

src/utils/find.ts
src/vueWrapper.ts
tests/findComponent.spec.ts

See: https://github.com/vuejs/vue-test-utils-next/issues/211 (resolves #211)
This seems like a kind of strange thing to have, but I would like to keep back-compat as much as possible. Apparently this worked in V1 (no idea what the use case is).
I could not get this to work without giving a `name` to the component; so it's not perfect in terms of back-compat.

fix: allow finding root component

---

src/config.ts
src/domWrapper.ts

Currently `config.plugins.DOMWrapper.install` does not work

[fix] apply DOMWrapper plugins in constructor

---

src/createDomEvent.ts

This resolves #218 which may be caused by a simple typo in the codebase.
It seems like a core intent of `getEventProperties` is to source default properties of different types of DOM events from the 'dom-event-types' dep and provide them as properties for new events. However, it looks like the `cancelable` property is not being added to the returned object.
This change resolves the bug I'm seeing in #218 by allowing `click` events to have `preventDefault` work correctly.
I'd be happy to add a test case to test against regression here, but it doesn't seem like a logic bug or something that's likely to be reverted if my above assumptions seem reasonable.

fix: set default event.cancelable from dom-event-types

---

package.json
tests/components/Suspense.vue
yarn.lock

Since Vue 3.0.1, the error handling in Suspense has changed to be consistent with Vue 2.
See https://github.com/vuejs/vue-next/commit/4d20ac8173f84c87288255dcc03c62a6ee862a23
@lmiller1990 This does not need to be released right away, it's just to keep VTU up-to-date with the latest Vue release (I was trying to reproduce another issue when I stumbled on this failing test).

fix: error handling in suspense

---

src/mount.ts
src/vueShims.d.ts
test-dts/mount.d-test.ts

Support for the DefineComponent type 
There's an issue with the passing the data function:
```ts
// TODO it should work
mount(ShimedComponent, {
data() {
return {
a: 1
}
}
})
```

fix: support for DefineComponent shim

---

src/constants.ts
src/mount.ts

Related: https://github.com/vuejs/vue-test-utils-next/issues/219
@afontcu seems we can remove this id. I am not sure about the div - what should we be attaching to?
Also, does testing library use `attachTo` by default? We need *something* to mount on - if you are using attachTo, however, maybe we can use that element to mount on, instead of creating our own DIV here?

refactor: do not pollute markup with useless id

---

rollup.config.js

Hi!
I'm trying to test `vue 3` using `vite` with `vue-test-utils-next`. There's a missing build for `esm-browser` because `esm-bundler` uses `@vue/compiler-dom` and not `@vue/compiler-dom/dist/compiler-dom.esm-browser` which is needed if you want to run VTU in browser using `vite`.
This PR is a showcase of how this fourth – `vue-test-utils.esm-browser.js` – build could look like.

Add ESM browser build

---

src/config.ts
tests/config.spec.ts

This allows users to directly attach global properties like mocks and provide without checking it before:
```js
// this pr removes the need of
config.global.provide = config.global.provide || {}
```

feat: default values for global.config

---

src/utils/find.ts
src/vueWrapper.ts
tests/findComponent.spec.ts

#187 
That was easy 🤔 ... too easy ... must have broke something? Heh.

fix: findComponent with functional components

---

package.json
src/utils.ts
tests/components/ClassComponent.vue
tests/features/classComponent.spec.ts
yarn.lock

Class component is not working when declared in a SFC file.
https://github.com/vuejs/vue-jest/issues/297 related maybe.
I will continue adding more test cases here.

wip: class component support

---

src/mount.ts
src/vueWrapper.ts

fix: delete useless code

---

src/index.ts
src/mount.ts
src/types.ts

Having `MountingOptions` available in Vue Testing Library will improve greatly the DX of people using the library.

Export MountingOptions interface

---

.github/workflows/ci.yml

(source: https://nodejs.org/en/about/releases/)
We could drop node 10 as it is quite old and in maintenance mode, but it's fine I guess.

Add newer node versions to CI

---

src/mount.ts
test-dts/mount.d-test.ts
test-dts/shallowMount.d-test.ts

fix #251
This was caused because `vue-class-component` dependency was not made optional or as a dev, so the import `VueContructor` would always be `any`, making all the `mount` and `shallowMount` to be caught by that overload.
I've removed the dependency on `VueContructor` on the `mount`, made it a bit more generic, this might break if the types changes on the `vue-class-component` (which I think is unlikely) 
@ktsn can you just validate if this overload is enough?
```ts
// Class component - no props
export function mount<V>(
originalComponent: {
new (...args: any[]): V
registerHooks(keys: string[]): void
},
options?: MountingOptions<any>
): VueWrapper<ComponentPublicInstance<V>>
// Class component - props
export function mount<V, P>(
originalComponent: {
new (...args: any[]): V …
```

fix(types): Fix mount and shallowMount types

---

src/components/RouterLinkStub.ts
src/mount.ts
src/stubs.ts
tests/mountingOptions/stubs.global.spec.ts

Maybe @cyberb can have some input here too.
This addresses https://github.com/vuejs/vue-test-utils-next/issues/249
At the moment `stubs` will only work for locally registered components. For global ones (like `<router-link>`) you currently must registered a component globally to stub it, eg:
```js
mount(Foo, {
components: {
RouterLink: {
render() { return h('div') }
}
}     
})
```
Many people expect this to work (I also do)
```js
mount(Foo, {
global: {
stubs: {
RouterLink: {
render() { return h('div') }
}
}
}     
})
```
This PR takes anything from `global.stubs` and registers a global stub.

issue-249 feat: stub global components

---

src/config.ts
src/vueWrapper.ts
tests/features/plugins.spec.ts

I noticed you cannot actually access `options` in your plugin, which makes them not very useful. I fixed it.
Recommend reviewing with whitespace OFF, I removed a useless `describe`, which made the diff bigger that it should be.

fix: ensure plugins receive options correctly

---

src/mount.ts
src/utils.ts
tests/mountingOptions/slots.spec.ts

resolves #221 
@lewishowles quick review/test if you can, since you have a use case for this feature.

fix: handle slots correctly

---

src/mount.ts
src/types.ts
test-dts/mount.d-test.ts
test-dts/shallowMount.d-test.ts

fix #237 
Fix issue of not making default properties as optional.
Allow to pass extra props (same behaviour as `h`) 
Commented on tests which prevented extra props.

types: fix mount infer prop type

---

src/config.ts
test-dts/plugins.d-test.ts

feat(types): infer options in plugins

---

src/stubs.ts
tests/__snapshots__/shallowMount.spec.ts.snap
tests/mountingOptions/stubs.global.spec.ts
tests/shallowMount.spec.ts

resolves #213
I wonder if showing `[Object object]` is correct for object props. We could stringify, but it seems not stringifying is the default behavior in a regular browser.
Edit, I will fix the failing types soon.

fix: render props in stubs

---

package.json
yarn.lock

I think this dependency is not necessary. It was introduced in the very first commit on the repo, and I remember needed in my projects as well because of a typing issue in vue-next, but I think this has been solved for quite some time.

chore: remove @types/estree dependency

---

src/emit.ts
src/vueWrapper.ts
tests/emit.spec.ts

fix #352 
Emitted events are recorded against their component uid, so the events retrieved by `emitted()` doesn't contain child events.
Updated one of the tests to probe for this as well.
First stab at any typescript so please let me know if I've committed terrible type sins. :pray:

fix: record emitted events against each wrapper

---

package.json

When this entry is in, webpack never picks up on the module one,
which makes it go the wrong way. Since VTU is meant to be used in
Jest/Webpack/Rollup/Vite we shuold avoid breaking those.
I matched the exports of vue and vite here.

fix: remove the browser entry from package.json

---

src/config.ts
src/mount.ts
src/utils.ts
tests/config.spec.ts

linked #373 
I don't see why this should be required when trying to set up a single thing in the config. The user provided config is merged with the defaults: https://github.com/vuejs/vue-test-utils-next/blob/master/src/mount.ts#L322
Set it to `Partial` in case something will be required in the `GlobalMountOptions` down the line.
Edit:
This has stemmed from a confusion on how to use the the global config. Added a test to confirm how configs get merged.
+found and fixed an issue with renderStubDefaultSlot

Add test to confirm config merger

---

src/emit.ts
src/vueWrapper.ts
tests/emit.spec.ts

fix #391 
This is pretty ugly on a few levels and I think it needs some cleaning up, but I think it addresses the issue. Maybe going back to the old mixin is a better idea for native events, I think I'll leave that up to you because you know the history a bit better.
I added a test that covers I think a basic exploration of the problem being solved.
Again, I'm an absolute TS novice, :pray: for me.
Looking at this code again, do we need to add a way to clear events similar to jest's `mockClear()`?

fix: record native events against each wrapper they bubble through

---

README.md
docs/.vitepress/config.js
docs/api/index.md
docs/guide/advanced/async-suspense.md
docs/guide/advanced/slots.md
docs/guide/essentials/easy-to-test.md
src/types.ts

docs: Cleanup and update API docs

---

src/mount.ts
tests/vm.spec.ts

Allow to spy on `wrapper.vm` with jest.
Fixes #309 
BLocked by https://github.com/vuejs/vue-next/pull/3105

fix: spy on wrapper.vm with Jest

---

rollup.config.js

Currently we have a warning when building VTU.
```
(!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
```
`@rollup/plugin-replace` introduced a new option in v2.4.0 to prevent accidental assignements.
See https://github.com/rollup/plugins/blob/master/packages/replace/CHANGELOG.md#v240
This probably does not matter for us, but let's get rid of the warning.

chore: remove rollup replace warning

---

src/utils/isElementVisible.ts
tests/isVisible.spec.ts

A quick addition so the method takes all styling into account.

feat: make isVisible more comprehensive

---

src/emit.ts
tests/props.spec.ts

reverts changes made in https://github.com/vuejs/vue-test-utils-next/pull/393. two way syncing can be done using the following code
```ts
const wrapper = mount(component, {
props: {
modelValue: 1,
'onUpdate:modelValue': async (modelValue: number) => wrapper.setProps({ modelValue })
}
})
```
discussion regarding potential additional mount option for v-model usage continues in https://github.com/vuejs/vue-test-utils-next/discussions/279
closes #440

fix: revert automatic two way sync of v-model prop values

---

docs/guide/advanced/component-instance.md

docs: component instance

---

src/mount.ts
tests/mountingOptions/global.components.spec.ts

Coming from https://github.com/posva/vue-router-mock/issues/96
The warning happens because I do this: https://github.com/posva/vue-router-mock/blob/v2/src/injections.ts#L37-L41
I think this change is useful to toggle stubs with `stubs: {RouterLink: false}`

fix: allow global components to be stubbed

---

package.json
test-dts/getComponent.d-test.ts
test-dts/index.d.ts
test-dts/mount.d-test.ts
test-dts/plugins.d-test.ts
test-dts/shallowMount.d-test.ts
test-dts/tsconfig.tsd.json
test-dts/wrapper.d-test.ts
yarn.lock

TSD has weird regressions with vue-next 3.0.9, maybe due to TS 4.2.
Instead of figthing it, let's adopt what the other Vue projects did and replace TSD with a plain `tsc` check.
See https://github.com/vuejs/vue-next/commit/97dedebd8097116a16209664a1ca38392b964da3 for example for a similar commit on vue-next

chore: remove tsd

---

docs/guide/advanced/stubs-shallow-mount.md
tests/mountingOptions/stubs.global.spec.ts

Closes #514
Add section in docs for stubbing an async component and also a test case for this scenario.
It is required to set a name in your async component and use this name in `global.stubs`.

docs: Add docs and test for stubbing an async component

---

docs/guide/advanced/stubs-shallow-mount.md
src/stubs.ts
tests/__snapshots__/shallowMount.spec.ts.snap
tests/mountingOptions/stubs.global.spec.ts
tests/shallowMount.spec.ts

I have dealt some more with stubbing out an async component.
With this PR I want to allow to stub out the async component without the need to provide a name and use `async/await`.
The async component can now be stubbed out the same way as a sync component:
```js
// AsyncComponent.js
export default defineComponent({
name: 'AsyncComponent', // Not required any more
template: '<span>AsyncComponent</span>'
})
// App.js
const App = defineComponent({
components: {
MyComponent: defineAsyncComponent(() => import('./AsyncComponent'))
},
template: '<MyComponent/>'
})
// App.spec.js
test('stubs async component without resolving', () => {
const wrapper = mount(App, {
global: {
stubs: {
MyComponent: true
}
}
})
// No need to use await flushPromises() …
```

feat: Allow stub out async component without name and without need of async/await

---

src/vueWrapper.ts
tests/emit.spec.ts

fix #444 
I experimented with attaching the native event listener to the component's parentElement, hoping that vue's native event emitting behaviour would provide what we really want to collect, but this broke a couple of other tests.
Instead I opted to simply filter out any native event names that appear in `emits` while attaching our enumerated native event listeners. The added test passes and nothing else breaks so I think this should be adequate to fix #444.

fix: don't record native events that are included in emits option (#444)

---

src/dataMixin.ts
src/mount.ts
tests/setData.spec.ts

Make data via mounting option reactive.
Closes #538

Fix set data reactive

---

src/vueWrapper.ts
tests/emit.spec.ts

The fix introduced in #521 only accounts for emits define as an array, but it can also be define as an object.
The latest rc.5 release breaks on components that use an object to define emits with:
TypeError: emits.includes is not a function
This commit fixes the unit test to have both cases check, and the relevant code to properly handle the object case.

fix: emits can be an object

---

docs/guide/advanced/http-requests.md

This PR removes the use of the `flushPromises` package in the code examples in favor of the `flushPromises` function from the `@vue/test-utils` package as it is already the case in the other examples found in the documentation.

fix: use flushPromises from @vue/test-utils in the docs

---

tests/features/async-components.spec.ts

The test does not need to declare a full configuration.
This will break compilation with Vue v3.1 as a new `compilerOptions` has been added to `AppConfig`.
Refactoring the config to be a partial one is more accurate and awill allow us to upgrade to v3.1 when it's out.

refactor: app config in test

---

docs/migration/index.md

Closes #593
Looks like I missed it when migrating from repos, so here it is again :) It is a simple copy&paste from old file (plus some tweaks), we might be missing some additional content that we can add afterwards

docs: Port migration page from old repo

---

docs/api/index.md
docs/migration/index.md

Should fix the CI builds again (Netlify was failing because of dead links in docs).

docs: fix dead links

---

docs/guide/advanced/slots.md
src/mount.ts
src/utils.ts
tests/components/WithProps.vue
tests/mountingOptions/slots.spec.ts

Continue from: https://github.com/vuejs/vue-test-utils-next/pull/573
resolves https://github.com/vuejs/vue-test-utils-next/issues/482
Now you may pass an array of slots. There is some TS weirdness, I have no idea if the types are wrong or my code is wrong, but everything works as expected.

feat: array of slots

---

src/config.ts
src/mount.ts
src/stubs.ts
src/utils.ts
tests/mountingOptions/global.components.spec.ts
tests/mountingOptions/stubs.global.spec.ts

I'm sorry to bother you guys 🙇🏻 
This pull request is for #606 
This caused that issue.
```js
stubComponents(global.stubs, global.renderStubDefaultSlot ? false : options?.shallow )
```
If global.renderStubDefaultSlot is true, options.shallow is ignored.
Hence, the issue caused.

fix: shallow config issue

---

docs/guide/advanced/http-requests.md

In Vue 3, passing `false` won't do the same thing as it did in Vue 2, and this test will fail.
https://v3.vuejs.org/guide/migration/attribute-coercion.html

Use null instead of false for disabled attribute.

---

src/mount.ts

Some types are now directly exported by vue-next, so we should not redeclare them.

chore: simplify mount types

---

src/errorWrapper.ts
tests/find.spec.ts

resolves https://github.com/vuejs/vue-test-utils-next/issues/638
Eh, a bit "smart" but avoids having to duplicate [everything like in Test Utils v1](https://github.com/vuejs/vue-test-utils/blob/dev/packages/test-utils/src/error-wrapper.js), which over the years has become tough to maintain.

fix: better errors for async find

---

.github/workflows/ci.yml
package.json
tests/components/ClassComponent.vue
tests/components/ScriptSetupWithChildren.vue
tests/components/Suspense.vue
tsconfig.volar.json
yarn.lock

This commit adds a check with volar to see if everything compiles fine.
This will allow to catch regressions when bumping Vue.
Currently, the ClassComponent test does not compile with Volar, so I'll open an issue to see if this is normal. 
The component is excluded from the check for now. 
(edit: this is not an issue see https://github.com/johnsoncodehk/volar/issues/245 I fixed the component in a second commit)
This also fixes a bunch of tiny things to make the PR green.

chore: add volar check

---

src/vueWrapper.ts
tests/find.spec.ts

This PR covers a kind of edge case.
Conditions: 
1. The component to test is nested in an element (so the parent element is not the mount wrapper)
2. the component doesn't render anything (so `$el` is a comment node)
3. The component is extracted with `wrapper.findComponent(Component)`
4. The test tries to use `extractedWrapper.find()` or `ExtractedWrapper.findAll()`
This will fail with an error being thrown:
> `TypeError: this.element.querySelector(All) is not a function`
This PR handles this case in a graceful way.

fix: Gracefully handle empty root node for nested component

---

src/vueWrapper.ts
tests/isVisible.spec.ts

I'd like to use isVisible in vueWrapper.
I think findComponent and isVisible interfaces are very useful for test, but actually findComponent returns vueWrapper instance which doesn't have isVisible interface.
Hence, below code doesn't work well...
```vue
const Comp = defineComponent({
template: '<div />'
})
const Root = defineComponent({
template: '<div><Child v-show=true /></div>',
component: {
Comp,
})
const wrapper = mount(Root)
console.log(wrapper.findComponent(Comp).isVisible()); // isVisible is not a function
```
What do you think this featureRequest ....???
I'm sorry if I'm against policy of design, but I guess this specification is more useful than current.

featureRequest: add isVisible to VueWrapper

---

package.json
rollup.config.js

https://nodejs.org/api/packages.html#packages_determining_module_system
Without `type: "module"` in the `package.json`, Node.js (and therefore [Jest](https://github.com/facebook/jest/blob/v27.0.4/packages/jest-resolve/src/shouldLoadAsEsm.ts), too) treats these `.js` files as CommonJS modules, which is incorrect. It is also [causing trouble in `vite-jest`](https://github.com/sodatea/vite-jest/blob/4d3c7be1ab908a2dbf457d5830f357f5ff404db1/packages/vite-jest/vite-server.js#L8-L12).

fix: use `.mjs` extension for ESM bundles

---

package.json

To help avoid shipping unbuilt releases like rc.7 in the future.

workflow: add prepublish script

---

src/stubs.ts
tests/mountingOptions/global.stubs.spec.ts

Current check for type of stub (`typeof stub === 'object'`) is too restrictive and does not take into account functional components. Fix this
As a side effect, this also fix using legacy components as stubs when using `@vue/compat`

fix: support passing functional components as stub implementation

---

src/stubs.ts
src/utils.ts
src/utils/find.ts
tests/findComponent.spec.ts

ATM finding stubbed component is extremely inconsistent. It depends on "register name" in `components: {}` section, if component has `name` itself and so on, making it hard-to-guess if it will work and creating a regression,  compared to @vue/test-utils 1.x
This PR introduces a cache (using `WeakMap`, so we do not have to care about cleanup) and makes `matches` aware of stub

fix: Allow finding component by definition when using shallow mount

---

docs/guide/advanced/stubs-shallow-mount.md
src/stubs.ts
tests/shallowMount.spec.ts

@vue/test-utils 1 [allowed to un-stub certain component](https://github.com/vuejs/vue-test-utils/blob/dev/test/specs/mounting-options/stubs.spec.js#L299-L310) by passing `false` as stub configuration
Recover and document this behavior

fix: opt-out of stubbing by passing false as stub

---

src/stubs.ts
src/utils/compileSlots.ts
tests/config.spec.ts
tests/shallowMount.spec.ts

Current implementation of `stubComponents` is extremely agressive and really stubs everything including wrappers created for slots and `SlotWrapper` component used internally
Fix this by adding set of components, which should not be stubbed and "whitelisting" SlotWrapper component and components created for slots
I find this approach way more clearer in terms of types, than adding extra field like "doNotStub" to any component, like it was done in @vue/test-utils 1.x

fix: do not stub slots content when using shallow mount

---

.github/workflows/ci.yml
jest.config.js
package.json
src/stubs.ts
src/utils/find.ts
src/utils/vueCompatSupport.ts
tests-compat/compat.spec.ts
tests-compat/jest-compat.config.js
types/compat.ts
yarn.lock

Vue 3.1 brings compat build, which is extremely important milestone in migrating huge codebases to Vue3.
`@vue/test-utils` plays surprisingly well with compat build and codebase in compat mode with only few changes required in code
Why changes are required? [Migration guide](https://v3.vuejs.org/guide/migration/migration-build.html) suggests enabling features via `configureCompat` as part of certain migration steps. If `RENDER_FUNCTION` feature is enabled, signature of render function will be similar to Vue2, so our stubs will not render slots. Luckily, we can override it, by explicitly setting `compatConfig` on our stub components (this has no effect if no compat build is in play).
Additionally a few magic hops are required for example for finding components declared with `Vue.extend`. …

feat: add @vue/compat initial support

---

src/mount.ts
src/utils.ts
src/utils/vueCompatSupport.ts
tests-compat/compat.spec.ts

~~Marked as draft, depends on #698 being merged~~
Ready to rock!
This PR adds correct handling for legacy functional components (`{ functional: true }`) when using compat build

Support legacy functional components in compat build

---

src/stubs.ts
tests/findComponent.spec.ts

Follow-up of #696 
When we're stubbing component (no matter with `mount` or `shallow: true`) we still want to find a component by searching original component definition

fix: find component by its definition when using stub without name

---

src/stubs.ts
tests/mountingOptions/global.stubs.spec.ts
tests/shallowMount.spec.ts

#607 [introduced](https://github.com/vuejs/vue-test-utils-next/pull/607/files#diff-840c8e77baceaebec1b759efa8bbb8505149fbd81c64bb120801388b66d839c4R162) a bug, when anonymous component will not be stubbed even when using `shallow: true`
Remove this special case - now it is properly handled by rest of the code (the only difference is that stubs will be now named as `anonymous-stub` which is kind of expected)

fix(shallow): correctly stub anonymous components

---

src/stubs.ts
src/utils.ts
src/utils/find.ts
src/utils/vueCompatSupport.ts
tests-compat/compat.spec.ts

Draft, waiting for #707 and #698
This PR adds correct extraction of component name for components created by `Vue.extend`

feat(compat): correctly stub components, wrapped in Vue.extend

---

src/stubs.ts
src/utils.ts
tests/findComponent.spec.ts

This one is a bit tricky. Sometimes we're reusing same stub for multiple components (it's fine when it is some kind of dummy stub). In this case previous naive approach taken in #704 will fail because we're having `stub -> type` mapping with stub as key.
To fix this, we're now generating unique stub (a very thin wrapper), making sure we could distinguish "stubs" for componentA and componentB when they are using same stub in `mount`
Marking as draft before #704 is merged

fix: findComponent should work using same stub for different components

---

src/constants.ts
src/mount.ts
src/stubs.ts
tests-compat/compat.spec.ts

This originally started as fixing obvious issue - we should not stub root when it is legacy functional component (`{ functional: true }`)
But it turns out that instead of adding more & more conditions we could switch to explicitly adding our Parent & root component to do-not-stub list and this greatly simplifies logic

fix(compat): do not stub legacy functional component root

---

src/stubs.ts
tests-compat/compat.spec.ts

If we will not pass `compatConfig` to `createStub` - slots might be located in other place when `RENDER_FUNCTION` compat is enabled
As usual - specifying `compatConfig` has no effect when non-compat build is used

fix(compat): correctly render default slot in stub if requested

---

docs/api/index.md
docs/migration/index.md

docs: findAll().at() migration notes

---

src/mount.ts
tests/mountingOptions/slots.spec.ts

We were not passing the entire component to `slots`, just the `render` function, so things like the lifecycle hooks were not executed.
closes #727

fix: correctly pass component definition as slot mounting option

---

tests/components/ComponentWithSlots.vue
tests/mountingOptions/slots.spec.ts

Volar is not happy with the variable names `boolean`, `string` and `object`.

chore: rename slot variables in tests

---

package.json
tsconfig.volar.json
yarn.lock

Now that https://github.com/johnsoncodehk/volar/issues/253 is fixed in vue-tsc v0.21.0, we can remove the workaround we had to disbale Volar on the unit tests.
It surfaced a few issues in the components that were added in the meantime, but these issues have been fixed by PR #756 #758 and #759

chore: remove volar workaround

---

src/utils.ts
tests/setData.spec.ts

fix(setData): do not concat previous and new array values

---

tests/components/EmitsEventScriptSetup.vue

`defineEmit` is replaced by `defineEmits` and using the deprecated version fails the test with Vue 3.2.0-beta.1

refactor: use defineEmits

---

tests/features/suspense.spec.ts

Removes the need for `setTimeout` in the suspense test

refactor: faster suspense test

---

tests/features/async-components.spec.ts

`jest.runTimersToTime` is deprecated and removed in jest 27

refactor: use jest.advanceTimersByTime in async test

---

src/mount.ts
tests-compat/compat.spec.ts

New day, new compat issue (this one discovered by working on migrating `bootsrap-vue` to compat build)
We need to unwrap component before mount, or (since typeof component will be function after `Vue.extend`)) it will be treated as function component and wrapped inside another one with "setup"

fix(compat): Do not wrap legacy options component with extra wrap

---

docs/api/index.md
src/mount.ts
src/stubs.ts
src/types.ts

Minor types tweaks - getting rid of `any` in definition of stubs global config

chore(types): improve types of stubs option

---

src/utils/vueCompatSupport.ts

Original issue: #765 
Basically bundlers are too smart and produce a warning about missing export when they see the line:
```js
const fakeCmp = Vue.extend({})
```
**somewhere** in code even if actual execution of this line is guarded (by checking `GLOBAL_COMPAT` flag)
We now use alternate approach for "reaching" `Vue.extend` which does not trigger this warning

fix(compat): avoid warning about non-existing export, fix #765

---

docs/guide/extending-vtu/community-learning.md

This could be greatly improved in both quality and quantity, but just thought that it's better than having an empty page.

docs: Add learning links

---

src/stubs.ts
tests/mountingOptions/global.stubs.spec.ts

Fixes #810 
Basically we need to cache our stubs so we do not create new stubs each render.
We already had this thing in place long ago for our automatic stubs (created either by shallow or with stub value set to `true`)
This PR uses same logic and unifies "storage" of created stubs

fix(stubs): Do not create stubs across multiple renders, fix #810

---

docs/api/index.md
src/utils.ts
src/vueWrapper.ts

With more & more complexity in the code it would be great to utilize all powers of typescript.
While we can't get rid of all instances of `any` (because this will cause a lot of different inconveniences for examples when you're using `props()) - we should use `unknown` when possible to indicate "all possible values" - this allows TypeScript to use all it's inference power
For the same reason I've switched from overloads to using compound type for `selector` in `findComponent` - without `any` TypeScript performs better checks (and even caught that we were doing unneeded search when searcing by ref)

chore(types): improve types of vueWrapper

---

docs/api/index.md

findAll example test looks for <tr> elements but <span> elements are used inside template

docs: match findAll example template and test

---

docs/api/index.md

Attempt to untangle the meaning of "global" application config and "global" test suite config.  Adjusted anchors to point to test suite config examples when expected.
Related to: https://github.com/vuejs/vue-test-utils-next/issues/684

docs: Clarity in anchors/wording for global/test-suite config.

---

src/utils/find.ts

Basically, this is a proper finisher for #188 - we can avoid going over same vnodes again and again if we do not queue them multiple times - as long as we queue `node.component.subTree` - no need to queue`subTree.children` - they will be aggregated later by calling `aggregateChildren(nodes, node.children)`
@lmiller1990 I think you will be happy to see we're finally simplifying this part a bit :)

chore(find): simplify vnode traversal

---

docs/api/index.md
src/vueWrapper.ts
tests/findComponent.spec.ts

This is first part of fix related to #716 
After certain consideration, I've decided that expected behavior should be not throwing error, but returning empty wrapper instead.
My reasoning is based on three points:
1. Passing `ref` to `findComponent` is perfectly valid syntax. So if we're looking for component with specific ref and it does not exists - why should we complain about HTML element with same ref? We simply should not care
2. (Real world example from gitlab codebase). Consider having `<component ref="hello" :is="foo">` where `foo` under certain conditions is resolved either to `<div>` or to component (let's say `<Note>`). Consider having table syntax test, where we pass certain props... and if we throw, it definitely will look ugly and wrong instead of just checking for …

fix: do not crash findComponent if ref is pointing to html element

---

src/mount.ts
src/utils.ts
tests/components/ComponentWithSlots.vue
tests/mountingOptions/slots.spec.ts

I've originally [encountered](https://github.com/bootstrap-vue/bootstrap-vue/blob/5bf6733/src/components/table/table-colgroup.spec.js#L31) this issue while porting bootstrap-vue to Vue3
All known (at least to me and in mentioned stack overflow :stuck_out_tongue: question) methods of checking if something is HTML reports false for `<col><col><col>` because `<col>` is considered valid tag only inside `table -> colgroup`
In order to fix that I simply removed check if it is HTML and always wrap slot provided as string into `<SlotWrapper>`
This has a downside - if code under test relies on knowing that slot will always have raw strings - it will be confused by wrapper. User could workaround it with passing slot as function:
```js
slots: {
'some-slot': () => h('Something which should be just …
```

fix: Always wrap string passed to slot in a helper component

---

src/mount.ts

Good code is dead code :)
Stubs created inside `mount.ts` for `global.stubs` were never called, since they were replaced by `stubComponents during `transformVNodeArgs` pass (which is intended and correct)
Removed unneeded code and provide explanation why it works in this way
Super happy to have stubs code living in one place instead of two now :)

chore(stubs): simplify global stubs registration

---

src/vueWrapper.ts
tests/findComponent.spec.ts

When we're using `findComponent` on recursive component, the result is pretty unexpected - if our selector matches root - it will return first nested instance. Considering #211 I've made sure that if root matches - it always takes priority
This resulted in failing test which literally expects other behavior. After some consideration and verifying this is behavior of vue-test-utils v1 [CodeSandBox](https://codesandbox.io/s/charming-framework-qzilk?file=/src/App.test.js:276-327) - I've dropped offending test intentionally (@dobromir-hristov will be cool if you could look and approve that)

fix(findComponent): return root instance if it matches

---

src/mount.ts
src/utils/compileSlots.ts
tests/mountingOptions/slots.spec.ts

Exposing extra "SlotWrapper" in certain cases makes VTU behavior different from browser one, as mentioned in #389 
This PR gets rid of "exposing" anything wrapping slot, by providing same function, as if slot was passed in template
~~This PR depends on #815 so it is marked as draft for now :)
Changes specific to this PR could be viewed at d3a147c~~

fix(slots): does not expose extra wrapper of slot content, fix #389

---

docs/api/index.md

Fixed a typo in the `get` method description
Gets **an an** element and returns a `DOMWrapper` if found. Otherwise it throws an error.
Gets **an** element and returns a `DOMWrapper` if found. Otherwise it throws an error.

Fix typo in get method description

---

docs/guide/advanced/http-requests.md

This PR fixes the test in the section "Making HTTP Requests" (https://next.vue-test-utils.vuejs.org/guide/advanced/http-requests.html) and makes some explain.
**Why it is necessary?**
Because it has been mentioned in #868.
The previous test is broken because you cannot access variables/methods unprefixed with `mock`. Follow this: https://jestjs.io/docs/es6-class-mocks#calling-jestmock-with-the-module-factory-parameter.
> A limitation with the factory parameter is that, since calls to jest.mock() are hoisted to the top of the file, it's not possible to first define a variable and then use it in the factory. An exception is made for variables that start with the word 'mock'. It's up to you to guarantee that they will be initialized on time! For example, the following will throw an …

docs: fix test in making http requests

---

docs/api/index.md
src/types.ts
src/vueWrapper.ts
test-dts/getComponent.d-test.ts
tests/attributes.spec.ts
tests/findAllComponents.spec.ts
tests/findComponent.spec.ts
tests/getComponent.spec.ts

This brings VTU2 behavior in line with VTU1 
Closes #689

fix: remove ability to use findComponent with DOM selector

---

src/mount.ts
src/stubs.ts
tests/findComponent.spec.ts
tests/getComponent.spec.ts

Pretty self-describing, I hope :)

fix(find): allow finding root without name

---

src/baseWrapper.ts
src/domWrapper.ts
src/vueWrapper.ts
tests/findAllComponents.spec.ts
tests/findComponent.spec.ts

This is a follow-up (lol) of https://github.com/vuejs/vue-test-utils/issues/1703#issuecomment-707134340
Chaining `.find` with `.findComponent` has multiple usages in GitLab and other projects (for example `bootstrap-vue`) (see https://github.com/vuejs/vue-test-utils/issues/1703#issuecomment-707085682) and actually was a blocker for us to move our API from `find` to `findComponent` in VTU v1 :)
This PR adds chaining to VTU v2. Additionally it enables "workaround" if someone **urgently** need to find some known component by CSS selector as mentioned in #689 (assuming #896 is merged): 
```js
wrapper.find('.foo').findComponent(Hello)
```
will match `<Hello class="foo" />`. I like both that we have possibility to do that if really needed (for example for gradual migration) and that it looks & …

feat(find): allow chaining find with findComponent

---

docs/guide/advanced/vue-router.md

Adds examples on how to mock vue-router 4 when using `useRouter` and `useRoute` on a setup function through composition API.

docs: vue-router composition api example

---

tests/findComponent.spec.ts
tests/isVisible.spec.ts

The Vue compiler started complaining about badly formed templates.

chore: fix test warnings

---

docs/guide/advanced/component-instance.md

[old link](https://github.com/vuejs/rfcs/blob/script-setup-2/active-rfcs/0000-script-setup.md#closed-by-default) invalid.

docs: fix "closed by default" link

---

src/emit.ts

Rollup was complaining about:
```
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
src/emit.ts
1: var _this = this;
^
2: import { setDevtoolsHook } from 'vue';
3: var events;
```
This commit gets rid of the warning by using `{}` instead of `this` for `setDevtoolsHook` second parameter.
`vue-next` uses `getGlobalThis()` as the second parameter, which ultimately falls back to `{}`.

chore: fix build warning

---

docs/guide/advanced/vue-router.md

Adds missing brackets in "Testing useRouter and useRoute within setup" example and closes https://github.com/vuejs/vue-test-utils-next/issues/1055

Add missing brackets in useRouter example

---

src/vueWrapper.ts
tests/components/DefineExposeWithRenderFunction.vue
tests/expose.spec.ts

Fixes #1065
When we are testing a component with a render function returned by the setup,
then its proxy will be empty.
The behavior difference can be seen in vue-next [here](https://github.com/vuejs/vue-next/blob/d19cfc0503dddbded5e599bef0965aba3d25ca28/packages/runtime-core/src/component.ts#L674).
In that case, `wrapper.vm` will be empty if we return `vm.$.proxy`.
To handle it, we return `vm` directly for such components,
allowing at least what is exposed publicly to be available on `wrapper.vm`.

fix: expose with render function

---

src/domWrapper.ts
tests/find.spec.ts

`@vue/test/utils` v1 returns DOMWrapper itself if it matches selector passed in `find` (this is identical to `findComponent` behavior which was fixed in https://github.com/vuejs/vue-test-utils-next/pull/834)
This is heavily used in (for example) `bootstrap-vue` (ignore legacy `.wrappers` part):
```js
expect($inputs.wrappers.every(c => c.find('input[type=checkbox]').exists())).toBe(true)
```
Although I'm not 100% happy with such behavior I think we should match v1

fix(find): Allow finding self from DOMWrapper

---

src/utils/find.ts
tests/findComponent.spec.ts

This fix swaps priority order when searching for component by name to make `displayName` respected.
It is important for functional components: 
```js
const Cmp = () => 'hello'
// hey, I gave this one a displayName for A REASON
Cmp.displayName = 'FooComponent';
```
but is even more important for legacy functional components when used with `@vue/compat` - every single functional component will be named `Func` without this fix :)

fix(findComponent): favor displayName over name when searching

---

src/mount.ts
tests/mountingOptions/options.spec.ts

Vue 3.x keeps the behaviour we've had in Vue2: all unknown fields in component are passed as $options. This allows you to do following:
```
createApp({ ...App, test: 123 }).mount("#app");
```
and access test on `this.$options.test`
While not in a great use in modern Vue 3 code, this is still a great importance when we work with `@vue/compat` - you are still want to be able to pass router/store/etc. in "legacy" way to your component
This PR restores this behavior

fix(mount): pass unknown options to $options on mount

---

src/mount.ts
src/utils/vueCompatSupport.ts
tests-compat/compat.spec.ts

This one was quite tricky to debug :clock10: 
Basically, when dealing with legacy functional component we need to enable `FUNCTIONAL_COMPONENT` compatibility flag for `@vue/compat`
The problem is that we're wrapping this component inside `mount.ts` into script-setup component, which triggers Vue to render this component in "Vue 3 mode". ~~Usually this is not a problem - each component controls own compat flags using `compatConfig` but this is not a case for functional components - they do not have own instance, and compat config calculation is instance-based. This resulted into wrong normalization applied insid `@vue/compat` and result component simply ignoring event handlers inside test. To fix this we explicitly set `FUNCTIONAL_COMPONENT` flag in our "wrapper component" so Vue could …

fix(compat): handle listener, style and class in legacy functional components

---

docs/guide/advanced/teleport.md
src/config.ts
src/stubs.ts
tests/mountingOptions/global.stubs.spec.ts

Adds stubbing support for the `teleport` Vue component
Jest throws a warning:
```
console.warn
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
at <TeleportStub>
at <Anonymous ref="VTU_COMPONENT" >
at <VTUROOT>
```
I believe this has something to do with how teleport consumes slots and how the renderer provides them, but I couldn't figure out exactly what the issue was. Providing them as an object with a function didn't solve it (i.e. `{ default: getSlots }`.
Teleport seems a bit special in Vue land, I think this is okay, but please make sure it is ;)

feat: add ability to stub teleport

---

src/domWrapper.ts
src/vueWrapper.ts

Inject `createVueWrapper`. A little less readable but gets rid of the circular imports, which in my experience, can lead to big problems.

chore: remove circular import

---

src/baseWrapper.ts
src/domWrapper.ts
src/types.ts
src/utils.ts
src/utils/getRootNodes.ts
src/vueWrapper.ts
tests/find.spec.ts

This is the first step to implement proper support for multi-root components.
This will include:
* :heavy_check_mark:  fixes for `find` (this PR)
* fixes for `findAll` and `findAllComponents`
* fixes for `.html` and `.emits`
For sake of simplicity this PR is focused solely on fixing `find`

fix(find): implement proper find for multi-root components

---

src/baseWrapper.ts
src/domWrapper.ts
src/utils/getRootNodes.ts
src/utils/stringifyNode.ts
src/vueWrapper.ts
tests/html.spec.ts
tests/mountingOptions/slots.spec.ts

Just a minor fixes for `.html()` to work correctly with multi-root :tada:

fix(html): ensure wrapper.html() works correctly for multi-root

---

src/vueWrapper.ts
tests/emit.spec.ts

This PR makes our native event tracking behavior in line with Vue3 - see https://stackblitz.com/edit/vue-apcqqg?file=src%2FApp.vue for demo
Vue3 warns and does not track native events if:
* we render more than one element root node
* we render 0 element root nodes

fix(emitted): do not track native events on multi-root components

---

src/mount.ts
src/stubs.ts
src/utils/find.ts
tests/findComponent.spec.ts

Long-long ago, in the galaxy far-far away it started pretty simple: we've passed a stub for a component and VTU rendered this stub via `transformVNodeArgs` provided by Vue core:
We were able to find stub by stub (obviously, because VNode matched) and component by stub because [we've tracked relation between component and it's stub](https://github.com/vuejs/vue-test-utils-next/pull/696) (blue line)
Unfortunately, soon we've discovered that sometimes people use same stub for stubbing multiple components:
This was a problem, because we were unable to tell, if `Stub 1` was the stub of `Original component 1` or `Original component 2`
So, we've [introduced](https://github.com/vuejs/vue-test-utils-next/pull/705) a "specialized stub" concept - it is simply a copy of original stub, so for each …

fix(find): allow finding stubs by stub definition

---

docs/.vitepress/config.ts
package.json
yarn.lock

It looks like we can't upgrade because of the config declaration.
Vitepress 0.20+ now supports TS config with a helper function `defineConfig` to have type inference.
It looks like switching to that fixes our issue, and allows to upgrade Vitepress.

docs: fix vitepress config

---

docs/api/index.md

the example is not runnable without import `h`.

docs: Update index.md

---

src/stubs.ts
tests/components/ScriptSetupWithChildren.vue
tests/shallowMount.spec.ts

When mounting a component that has components defined with `defineAsyncComponent` the result of `type.name` is `AsyncComponentWrapper`. The `defaultName` contains the filename which should get precedence over the `type.name` to make stubbing work correctly.

Fix: Use defaultName when it exists to correctly stub async components

---

src/mount.ts
tests/mountingOptions/options.spec.ts

Closes #1104
`methods` is not a valid key in Vue Test Utils v2, but it existed in 0.x versions and some people got used to it. Thus, providing a warning message will help anyone updating their projects (or mental model!).
Any suggestion is more than welcome :)

fix: Remove `methods` key from mount

---

src/stubs.ts
tests/components/PropWithSymbol.vue
tests/props.spec.ts

resolves #1076
More context: https://github.com/ionic-team/ionic-framework/issues/24181
Basically when you do a stub that receives a `Symbol` as a prop, it ends up doing `<blah-stub sym="Symbol()">` which isn't allowed. Try it in your browser: `document.body.setAttribute('sym', Symbol())`.
I just filter out all the symbol props. Bit of a hack, but not a breaking change (passing a symbol as prop to a stub causes an error in both VTU v1 and v2). 
Happy to solicit any better work arounds for this issue, best I could come up with for now to unblock the issue in Ionic team repo.

fix: remove symbol props from stubs

---

tests/html.spec.ts

verifies https://github.com/vuejs/vue-test-utils-next/issues/563 is no longer a problem
closes #563

chore: add test case

---

src/stubs.ts
src/utils/componentName.ts
src/utils/find.ts
tests/findComponent.spec.ts
tests/mountingOptions/global.stubs.spec.ts

This PR will fix an issue when using script setup and trying to find a component without name:
```vue
<template>
<ComponentWithName />
<ComponentWithoutName />
</template>
<script setup lang="ts">
import ComponentWithName from './ComponentWithName.vue'
import ComponentWithoutName from './ComponentWithoutName.vue'
</script>
```
```ts
expect(wrapper.findComponent({ name: 'ComponentWithName' }).exists()).toBeTruthy() // Works
expect(wrapper.findComponent({ name: 'ComponentWithoutName' }).exists()).toBeTruthy() // Fails
```
I unified and centralized the retrieve of the component name from the stubs and the find, to have the same behavior when using component names.

fix: Allow find component without name in script setup by name

---

tests/emit.spec.ts
tests/expose.spec.ts
tsconfig.json
tsconfig.volar.json

This new option allows a better typechecking of components that expose variables.
See https://github.com/johnsoncodehk/volar/issues/805
Refs #972 as this partially fixes it

chore: use experimentalExposeScriptSetupContext for vue-tsc

---

package.json
tests/expose.spec.ts
tsconfig.json
yarn.lock

As the `experimentalExposeScriptSetupContext` has been removed, we need to workaround a type checking error

chore: bump to vue-tsc 0.30.1

---

docs/api/index.md

The API documentation of `GlobalMountOptions` has some difference
https://next.vue-test-utils.vuejs.org/api/#global vs. https://next.vue-test-utils.vuejs.org/api/#config-global

docs: Correct difference in GlobalMountOptions type

---

.github/workflows/ci.yml

Some dependencies are no longer compatible with Node v12 (vscode-jsonrpc).
Its end of life is in 3 months anyway.
This is what create-vue did as well: https://github.com/vuejs/create-vue/commit/cea1dcc1b1b4e7a33bea0db9a4febae88bae626a
This will allow #1209 to get merged

chore: drop node 12 support

---

docs/guide/advanced/async-suspense.md

Minimal explanation of how to test a component with an async `setup`, by mounting it inside a `Suspense`.
Fixes #1207

docs: async setup testing

---

src/utils.ts
tests/config.spec.ts

This PR fixes #1187 by doing 1st-level-pseudo-deep-clone merge of Vue's AppConfig (only the props that we know are objects - `globalProperties` and `compilerOptions`).
I was tempted to use lodash's `clondeDeep` but didn't want to bring another dependency. (looked at `lodash.clonedeep` as well but the `lodash.*` packages are not updated anymore). Not loving how `mergeAppConfig()` turned out but it does the job without additional dependencies. Open to alternatives :) 
This might break existing tests if they rely on the buggy behavior but i don't think it should be considered breaking changes 🤔
**Copy of the original issue and repro:**
> Thanks for the great work, guys! 🙇 I just noticed that when i pass the router plugin in a test, then the rest of the tests were inheriting the router.
> 
> …

fix: globalProperties config leak (#1187)

---

src/baseWrapper.ts
tests/components/MultipleRootRender.vue
tests/find.spec.ts

This PR will fix #1201.
I just used the same logic of `find` for `findAll` and unified this into one method. So same logic for `find` and `findAll` (except ref selector for `find`)

fix: findAll root nodes when using render function

---

tests/components/ScriptSetupWithChildren.vue

This should fix the error blocking the upgrade to vue-tsc v0.31.1
```
tests/components/ScriptSetupWithChildren.vue:10:1 - error TS1232: An import declaration can only be used in a namespace or module.
10 import ScriptSetup from './ScriptSetup.vue'
~~~~~~
tests/components/ScriptSetupWithChildren.vue:11:1 - error TS1232: An import declaration can only be used in a namespace or module.
11 import WithProps from './WithProps.vue'
~~~~~~
```

fix: static imports

---

docs/guide/extending-vtu/plugins.md
src/config.ts
src/stubs.ts
tests/features/plugins.spec.ts

Adds a new plugin API to `config.plugins` called `createStubs` which will override the default stub creation provided by VTU.
Usage:
```ts
config.plugins.createStubs = ({ name, component }) => {
return defineComponent({
render: () => h(`custom-${name}-stub`)
})
}
```
When VTU creates a stub either from `shallow: true` or `stubs: { ChildComponent: true }`, then the provided function will be called.
This will allow to implement different custom logics which are mentioned here:
* https://github.com/vuejs/vue-test-utils-next/issues/773#issuecomment-885182483
* https://github.com/vuejs/vue-test-utils-next/issues/945
* https://github.com/vuejs/vue-test-utils-next/pull/1174
* https://github.com/vuejs/vue-test-utils-next/issues/1179
* https://github.com/vuejs/vue-test-utils-next/issues/69
I have …

feat: Add createStubs plugin hook

---

package.json

It turns out we are stilll using it, and that removing the explicit dependency bothers Yarn 2.
Hopefully fixes #1306
This reverts f61b8aeb84352b29e29666326939531cd81c3bd6

chore: re-add @vue/compiler-dom dependency

---

src/utils/componentName.ts
tests/components/DynamicComponentWithComputedProperty.vue
tests/shallowMount.spec.ts

This PR adds a minimal set of tests to describe issue #1277, which regards how dynamic components, when shallow mounted, are stubbed with the name of a computed property that returns a component's name instead of the component itself.
The test component outlines the most extreme error case: a computed property does not need to be referenced in order to trigger the issue, it merely needs to both exist and return the component that is directly referenced.
This PR now also implements a possible simple fix for the issue.
cc: @cexbrayat

test: Add tests for shallowMount issue with dynamic components

---

docs/api/index.md

Since https://github.com/vuejs/test-utils/pull/1094 find supports element refs. This PR adds the new use case to the docs.

Add docs for find by element ref

---

src/components/RouterLinkStub.ts
tests/RouterLinkStub.spec.ts

resolves #848 
Added a default "empty" route object based on what I've seen coming out of vue-router, and basic stupid values for the rest of the slot props. In my opinion, anyone who needs `RouterLink` to be a bit smarter can create their own stub or use the real thing.
I also added the `custom` prop behaviour since it was easy to lift from the real `RouterLink` but it's probably not necessary, I'd be happy to remove that.
I added some tests around `RouterLinkStub` just to verify my implementation, also happy to remove them if they add unnecessary weight to the test suite.

fix: pass RouterLink slot props to RouterLinkStub slot

---

src/baseWrapper.ts
src/domWrapper.ts
src/vueWrapper.ts
tests/components/ParentComponent.vue
tests/find.spec.ts

This is alternate approach to fix #1233 
Other approach: #1377
What I'm liking about this approach:
* we're not introducing any flags 
* we're just moving `findAll` implementation to `DOMWrapper`/`VueWrapper` to distinguish behavior on Vue wrapper / DOM (semantics :1st_place_medal: )

fix(find): find and findAll should not find itself on DOM wrappers

---

docs/guide/advanced/vue-router.md

This PR fixes a typo in `vue-router.md`: "at it's core" 👉  "at its core".

Fix typo in vue-router.md

---

src/baseWrapper.ts
src/interfaces/wrapperLike.ts
test-dts/wrapper.d-test.ts

fix(type): add undefined type to attributes() for missing key

---

src/interfaces/wrapperLike.ts

This fixes #936 (again). It was fixed by #1184, but then re-broken
by #1180.

fix: make imports in wrapperLike relative (again)

---

docs/api/index.md

Copies `RouterLinkStub` portion from the v1 api docs with a small addendum re: slot content.
Added after a comment in #1381 pointed out these were missing.

docs: add RouterLinkStub to api docs

---

src/utils.ts
tests/features/compat.spec.ts

This option was not used, and not exposed in the typings.
This was misleading as developers can imagine that setting `compilerOptions` in the config is the proper way to configure Vue.
This should be done either by:
- setting the options via https://github.com/vuejs/vue-jest#global-jest-options for Jest and vue-jest
- setting the options in Vite directly for vitest

fix: remove compilerOptions from config

---

docs/guide/advanced/reusability-composition.md

docs: Add testing composables section

---

src/stubs.ts
tests/mountingOptions/global.stubs.spec.ts

fix #929 
I came across an equal issue when using `shallow: true` but still want to use the real `teleport`. This ensures to use the real component when using
```js
const wrapper = mount(Comp, {
shallow: true,
global: {
stubs: {
transition: false,
teleport: false,
'transition-group': false
}
}
})
```

fix: disable stubs for built-in components on shallow

---

docs/api/index.md
docs/guide/advanced/component-instance.md

relates #1195
I added some info about the `WrapperLike` type to the docs. I'm not sure whether the Signature section in the API Reference is understandable

docs: Add type info about WrapperLike on findComponent

---

src/mount.ts
tests/props.spec.ts

fix: forward Ref prop on mount

---

src/baseWrapper.ts
tests/findComponent.spec.ts

fix: findComponent with ref inside v-for

---

src/utils/compileSlots.ts

Fix for #1166. Render function requires ctx as the first param. This was not being passed in so was always null and erroring out. Bit confused why this only seems to be happening for Mocha users. Seems like it would be null for everyone.

fix: string slot null ctx in renderFn

---

src/vueWrapper.ts
tests/element.spec.ts
tests/text.spec.ts

fix #1461 
`wrapper.element` did not return the correct element for some edge cases with multiple root nodes.
For example when using another component in template which has multiple root elements:
```vue
<template>
<WithMultipleRoots />
</template>
```
This has led to issues with `wrapper.text()` (#1461)
I had to differ between stateful and functional components to avoid other failing tests. Maybe not all edge cases covered.

fix: wrapper.element with nested multiple roots

---

package.json

fix: fix module resolution for esm file

---

src/mount.ts
tests/mountingOptions/props.spec.ts
tests/setProps.spec.ts

fix: Pass props to functional component

---

src/vueWrapper.ts
tests/element.spec.ts

This PR fixes `wrapper.element` retrieval for components with slot :)

fix(wrapper): fix wrapper.element for component with slot

---

src/domWrapper.ts
tests/findComponent.spec.ts

Let's assume following rendering structure: 
```mermaid
flowchart LR
RootComponent:::cmp --> NestedComponent:::cmp --> d(div.someclass):::dom
classDef cmp fill:blue,color:white;
classDef dom fill:darkgreen,color:white;
```
In this case
```js
mount(RootComponent).find('.some-class').find(NestedComponent).exists() // true
mount(RootComponent).find('.some-class').find(RootComponent).exists() // false
```
This is because `__vueParentComponent` will point to component who **actually** rendered dom node
To fix this we traverse ancestors of `__vueParentComponent` while their `vnode.element` is equal to current dom node and use resulted vue component as base for our search

fix(findComponent): allow finding top-level component

---

src/stubs.ts

Fixes the error:
```
src/index.ts → dist/vue-test-utils.esm-bundler.mjs...
[!] (plugin commonjs--resolver) Error: /home/runner/work/test-utils/test-utils/src/stubs.ts(77,14): semantic error TS2742: The inferred type of 'createStub' cannot be named without a reference to '@vue/compiler-dom/node_modules/@vue/shared'. This is likely not portable. A type annotation is necessary.
```
that we see when upgrading the lockfile in #1543

chore: add return type to createStub

---

src/components/RouterLinkStub.ts

When running tests in Vue 2 mode under `@vue/compat`, RouterLinkStub's render function dies because of the change to the `$slots` API. Declaring it as mode 3 helps it "just work" for users regardless of Vue compatibility mode.

fix(compat): declare RouterLinkStub as compatibility mode 3

---

src/index.ts

BaseWrapper isn't exported like VueWrapper and DOMWrapper, even though it is exported from baseWrapper.ts. This means that any consumers who want to use the type have to import it from `@vue/test-utils/dist/baseWrapper` instead of `@vue/test-utils` like the others.

fix(types): Export BaseWrapper from index.ts

---

package.json

See https://github.com/nodejs/modules/issues/445 for context. This package doesn't export its own package.json ever since the exports were added, which breaks some tooling I've written to help me with upgrading from VTU 1 to VTU 2 that tries to read the package.json to get the installed version.

export package.json from module

---

src/utils/getRootNodes.ts

TS v4.7 is now trying to compute the type more accurately in `flat()` and `Infinity` is not playing very well: it throws
```
src/utils/getRootNodes.ts:28:22 - error TS2589: Type instantiation is excessively deep and possibly infinite
```
I'm wondering if we really need to flatten infinitely, as the following lines call `getRootNodes` recursively on each element. But as I'm a bit fuzzy on how this part of the code works, I'd like more informed opinions 😉

fix(utils): getRootNodes flattens only one depth of children

---

tests/find.spec.ts

Extends some test for `findAll` with deep nested multiple root nodes. Created to test #1546. Feel free to merge or close if not necessary.

chore(find): extend tests with deep nested multiple roots

---

src/stubs.ts

Fixes #1550. 
I tried to write a test for this but it didn't pass. I think it's either because [vue-test-utils-compat](https://github.com/xanf/vue-test-utils-compat) is an additional step to make this work, or vue needs to be aliased to @vue/compat in the entire test suite, which I was a little hesitant to do. I saw that @vue/compat was already a dev dependency - not sure if we've tried to write tests like this in the past.

fix(compat): respect v-model in vue 2 with compat build

---

docs/.vitepress/config.ts

reference: https://vuepress.vuejs.org/theme/default-theme-config.html#algolia-search
close: #1512

fix: algolia appId

---

src/vueWrapper.ts
test-dts/wrapper.d-test.ts

I find pretty annoying usage of emitted with typescript:
```ts
expect(wrapper.emitted<unknown[]>('input')[0][0]).toEqual(testItems)
```
Requirement to specify `<unknown[]>` is pretty sad - since emitted events is always an array of arrays
This PR updates typings to simplify such use case

chore(types): improve typing of emitted

---

package.json
src/mount.ts
tests/components/AsyncComponent.vue
tests/components/ComponentWithoutName.vue
tests/components/Issue1476.vue
tests/components/Issue425.vue
tests/components/ParentComponent.vue
yarn.lock

There is a type-checking issue with VTU v2.0.1 (not with v2.0.0) when using the latest vue-tsc and components with script setup. This is reproducible in the repo if we bump t the latest vue-tsc (which necessitates to work around https://github.com/johnsoncodehk/volar/issues/1452).
We should fix and release, as people using TS and script setup will most likely encounter the issue.

repro: type-checking issue with script setup in v2.0.1

---

docs/installation/index.md

Update installation docs to suggest the installation of the `latest` tag instead of the `next` tag.
The latest tag currently points to `2.0.2` released 23 days ago while the `next` tag points to a fairly outdated version of `2.0.0-rc.18` released 7 months ago. It is probably a good idea to suggest latest stable version as the default version to be installed.

docs: update installation docs

---

tsconfig.json

This should unblock the bump to Vite 3.
I used es2016 as it is the [same target used by vuejs/core](https://github.com/vuejs/core/blob/main/tsconfig.json)

chore: use es2016 as a TS target

---

src/baseWrapper.ts
tests/find.spec.ts

fix: Make wrapper.find() enable to find ref in v-for directive

---

src/utils/find.ts
tests/findAllComponents.spec.ts

fix: duplicate results on findAllComponents with non-function slots

---

src/mount.ts

I'm not 100% sure why we need these with TS v4.8, probably a change needed by https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#improved-intersection-reduction-union-compatibility-and-narrowing
TS compiler is happy with these changes

chore: improve type for mount with TS v4.8

---

tests/features/compat.spec.ts
tests/features/suspense.spec.ts
tests/mountingOptions/global.stubs.spec.ts
vitest.config.ts

This fixes issues of some tests relying on others to run first.

chore: run tests in random order

---

.github/renovate.json5

It'll avoid two separate PRs for `vitest` and `@vitest/coverage-c8`

chore: group vitest updates

---

src/stubs.ts
tests/features/transition.spec.ts
tests/mountingOptions/global.stubs.spec.ts

The stubs for `<transition>`, `<transition-group>` and `<teleport>` don't have any props defined, which currently makes it impossible to test for those to be set correctly.
Took the props to add from https://vuejs.org/api/built-in-components.html.

fix: Add props to stubs for built-in components

---

src/stubs.ts

Slightly improves the types in the stubs function to avoid using any, as a follow up of #1767

refactor: stubs types

---

package.json
pnpm-lock.yaml
src/utils/componentName.ts
tests/components/AutoImportScriptSetup.vue
tests/mountingOptions/global.stubs.spec.ts
vitest.config.ts

When stubbing a component using the `<script setup>` syntax test-utils can't return its name correctly, so it skips the stub and the stub fails.There's an [issue ](https://github.com/antfu/unplugin-vue-components/issues/429) that describes the problem.
This is because `getComponentName()` function doesn't return its `__name` property.

fix: return the correct  name when stubbing a `script setup` component

---

src/mount.ts
tests/features/compat.spec.ts

* globalProperties might not be empty due to them being gathered from `Vue.prototype` when using compat build
By overwriting this properties any "legacy" plugin configuration, which adds properties via `Vue.prototype` will loose them, cause we will overwrite `globalProperties` with default empty object

fix(compat): do not overwrite globalProperties merge them instead

---

src/vueWrapper.ts
tests/element.spec.ts

While rendering array of vnodes in slot is discouraged (Vue complains about it and suggest using function for default slot for performance) - it is still valid according to https://vuejs.org/guide/extras/render-function.html#creating-vnodes
```js
// children array can contain mixed vnodes and strings
h('div', ['hello', h('span', 'hello')])
```
This fixes for me multiple tests wheb using `@vue/compat` with legacy codebase, where rendering array of vnodes was considered more performant :(

fix(element): return correct element for component which renders other component while passing array of vnodes in default slot

---

docs/guide/extending-vtu/plugins.md
src/baseWrapper.ts
src/vueWrapper.ts

as you mentioned in https://github.com/vuejs/test-utils/pull/1792 I created a custom plugin. if you want to use plugins in a typescript project you have to redefine the declaration of the `VueWrapper`. Therefore, I updated the docs

added typescript documentation to plugins.md

---

package.json

This is extremely simple, yet useful (in my opinion) change.
> NOTE: If a package being installed through git contains a prepare script, its dependencies and devDependencies will be installed, and the prepare script will be run, before the package is packaged and installed.
Since npm v5 npm executes `prepare` script when dependency is installed from git. By including `prepare` script it will allow our users use `@vue/test-utils` from `main` (or any other branch) even if release was not published to npm yet
However, this has a downside - after doing install locally (without include `@vue/test-utils` as dependency) it will be also executed. However, I feel here benefits outweight the downside
WDYT?

chore(scripts): add prepare script

---

docs/guide/advanced/stubs-shallow-mount.md
docs/migration/index.md
src/config.ts
src/utils.ts
tests/mountingOptions/global.stubs.spec.ts

Right now I've spent 30 minutes figuring why my default slots in stubs were not rendered, just to figure out, that our docs mention `global.renderStubDefaultSlot` as the way to control stub behavior, however we have **both** `config.renderStubDefaultSlot` and `config.global.renderStubDefaultSlot` with first being a preference
While **technically** this is a breaking change, I find an ability to define same thing in two places extremely confusing and fix for affected codebases will be trivial (swap `config.renderStubDefaultSlot` with `config.global.renderStubDefaultSlot`)
Otherwise, if we decide that we do not want to have such breaking change, I suggest swapping priority, so `config.global.renderStubDefaultSlot` will be taken into account before `config.renderStubDefaultSlot` and mark …

fix(config): Do not use config.renderStubDefaultSlot

---

src/vnodeTransformers/stubComponentsTransformer.ts
tests/props.spec.ts

`@vue/test-utils` v1 had special handing for functions in props when rendering stubs. 
This PR makes `@vue/test-utils` v2 behave in the same way, even reusing same placeholder from https://github.com/vuejs/vue-test-utils/blob/97fdf18cd96f2ce19036d497ec98f2f76fc7b066/packages/create-instance/create-component-stubs.js#L21
(this allows us to run snaphot tests of vue2 and `@vue/compat` and to verify snapshots identity)

fix(stubs): Do not render function body in stub

---

docs/guide/advanced/stubs-shallow-mount.md
src/mount.ts
src/stubs.ts
src/types.ts
src/utils.ts
src/utils/find.ts
src/vnodeTransformers/stubComponentsTransformer.ts
src/vnodeTransformers/stubDirectivesTransformer.ts
src/vnodeTransformers/util.ts
tests/findComponent.spec.ts
tests/mountingOptions/global.stubs.spec.ts

We're adding new vnode transformer (related to directives) and re-use our architecture for searching stubs to make sure that we still could find elements even after stubbing directives on them

feat(stubs): Allow to stub directives (fixes #1800)

---

package.json
pnpm-lock.yaml
tests/features/compat.spec.ts
vitest.config.ts

We were blocked by https://github.com/vitest-dev/vitest/issues/1978 but thanks to @sheremet-va help (see https://github.com/vitest-dev/vitest/issues/1978#issuecomment-1283747642) we now have a way to use the latest vitest releases.
It turns out that we needed to:
- alias `@vue/compat` to its ESM bundle
- use `Vue.extend` instead of `extend` in the `compat.spec.ts` file, as `extend` is not a named export

chore: update to vitest v0.24.3

---

docs/api/index.md
src/domWrapper.ts
tests/components/ComponentWithInput.vue
tests/setValue.spec.ts

Most taken from https://github.com/vuejs/vue-test-utils/pull/1554
closes #1768

feat(setValue): allow array for multiselect .setValue() method

---

src/vnodeTransformers/util.ts
tests/element.spec.ts
tests/findAllComponents.spec.ts
tests/mountingOptions/global.stubs.spec.ts

Fixes #1829
I'm not super convinced by this fix, but it indeed looks like @freakzlike intuition is right: we need to return the children as a function for Teleport to avoid the warning.
Maybe @xanf you have a better idea on how to handle that?

fix(stubs): teleport stub children as a function

---

.github/renovate.json5

Until https://github.com/vuejs/test-utils/pull/1834 is resolved, we exclude js-beautify from renovate updates.

chore: ignore js-beautify updates in renovate

---

src/mount.ts

Found this approach in main `@vuejs/core` repo
https://github.com/vuejs/core/blob/main/packages/runtime-core/__tests__/rendererTemplateRef.spec.ts#L23
I think this might be a good approach to simplify our codebase too!

chore(mount): simplify mount operation

---

src/baseWrapper.ts
tests/trigger.spec.ts

Fixes #1854
I'm not 100% convinced this is the proper way to fix it, but I don't have a better idea at the moment.
Setting `_vts` to Date.now() + 1 tricks Vue into thinking it has to handle the event even if `Date.now()` is faked and always returns the same value https://github.com/vuejs/core/blob/5ee40532a63e0b792e0c1eccf3cf68546a4e23e9/packages/runtime-dom/src/modules/events.ts#L100-L104
I hope this doesn't introduce other subtle issues. It would be great to only do this if the test is running with a fake Date, but I don't know how we can find out reliably for jest or vitest or even a manually mocked Date object.

fix(emit): force event handling even with fake timers

---

src/vueWrapper.ts
tests/expose.spec.ts

This fixes the issues with Vue v3.2.45 (see https://github.com/vuejs/core/issues/7103)

refactor: use a proxy for wrapper.vm

---

src/mount.ts
tests/mount.spec.ts

This is a workaround for https://github.com/vuejs/core/issues/7020
VTU v1, obviously do not blow up in this case

fix(mount): correctly work with component throwing on mount

---

src/vueWrapper.ts
tests/components/ScriptSetup.vue
tests/expose.spec.ts

Fixes #1859
The proxy needs to implement `defineProperty` to allow spying.

fix: allow spying on non-exposed script setup functions

---

package.json
pnpm-lock.yaml
src/mount.ts

Fixes #1872
Fixes the errors arising with script setup components:
```
tests/features/ScriptSetup_ToRefsInject.spec.ts:6:25 - error TS2769: No overload matches this call.
The last overload gave the following error.
Argument of type 'ComponentPublicInstanceConstructor<{ $: ComponentInternalInstance; $data: {}; $props: Partial<{}> & Omit<Readonly<ExtractPropTypes<__VLS_TypePropsToRuntimeProps<{ title: string; }>>> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10 more ...; $watch<T extends string | ((...args: any) => any...' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<__VLS_TypePropsToRuntimeProps<{ title: string; }>, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 5 more ..., {}>'.
Type …
```

chore: update to typescript v4.9.2

---

src/mount.ts
src/utils.ts
tests/components/ComponentWithI18n.vue
tests/components/HelloFromVitestPlayground.vue
tests/components/ScriptSetupWithI18n.vue
tests/mount.spec.ts
tests/mountingOptions/mocks.spec.ts
types/testing.d.ts

fix: allow to mock global function in script setup components

---

src/vnodeTransformers/stubComponentsTransformer.ts
src/vnodeTransformers/util.ts
tests/mountingOptions/global.stubs.spec.ts

It's very simple, the implementation is basically similar to what was done for `Teleport`, changing the rendering of children for `KeepAlive` to a function.

#1888: adding stubbing for keep-alive

---

src/vnodeTransformers/stubComponentsTransformer.ts
src/vnodeTransformers/util.ts
tests/mountingOptions/global.stubs.spec.ts

#1889 was lacking the support of the `KeepAlive` key in stubs

fix: allow to use KeepAlive or keep-alive in stubs

---

docs/migration/index.md

Context: https://github.com/vuejs/vue-test-utils/issues/1975#issuecomment-13595554 
As discussed, there are a couple of issues that the community faced while upgrading to `vue@3` + `@vue/test-utils@^2` but that are not directly related to them.
In an effort to make migrations smoother, a new section was added to the migration guide that lists some common problems with underlying test runners. These can be common, due to the fact that users took the opportunity to upgrade their test stack dependencies as well since they were already doing the testing library migration.
It adds a few issues with `jest`, it starts with an issue reported in the legacy [test-utils repo](https://github.com/vuejs/vue-test-utils/issues/1975) and another one that I've personally faced. 
Hopefully, the community …

docs: add section about test runners upgrade to migration guide

---

docs/guide/advanced/slots.md
docs/migration/index.md

Hello again 👋 
I had a bunch of specs that rely on the previous VTU1 behaviour, where slot scope was auto-exposed as a `props` object for string templates and realised that in VTU2 they are exposed as `params`
https://github.com/vuejs/test-utils/blob/39d86ad5abe71bac8d76c5b82f11f30225cf8673/src/utils/compileSlots.ts#L9-L11
While VTU1 docs [mention](https://v1.test-utils.vuejs.org/api/options.html#scopedslots) that behaviour, VTU2 docs [didn't **explicitly** do it](https://test-utils.vuejs.org/guide/advanced/slots.html#scoped-slots) as the only example provided used an `<template #scope="params">` which doesn't document the implicit behaviour if not providing a wrapping `<template>` tag.
Update both main docs and migration guide, since I believe this is a common _bump in the road_ while …

[docs]: improve slot scope auto exposing "params" behaviour

---

docs/guide/advanced/slots.md

The last change broke the conclusion section.

[docs]: fix broken  slots documentation

---

src/mount.ts
src/utils.ts
tests/mountingOptions/mocks.spec.ts

After a lot of discussion at https://github.com/vuejs/test-utils/issues/1869 and failed attempts to reproduce the issue I finally made the error happen and propose a fix. It's very ugly, but the tests are green and make more VTU@2 "customers" happy (at least one customer :) )
Using yet another vue internal property `__isScriptSetup`[^1][^2] to differentiate `<script setup>` components from Option API components with `setup()` hook since both fall in the `hasSetupState` block. The latter can be patched regularly without triggering Proxy trap set error that lead to the `2.2.3` patch in the first place (https://github.com/vuejs/test-utils/pull/1861), and only when patched like that, it actually works in all possible scenarios. 
The only reason for this to be acceptable code is because the …

Differentiate script setup from option api component with setup

---

docs/guide/essentials/easy-to-test.md

| Just fixing this issue with the docs: |
|:-:|
| ![image](https://user-images.githubusercontent.com/811806/211543987-012a3125-7ef9-41ee-83e7-2d15c1f937bf.png) |
| Before | After |
|:-:|:-:|
| ![image](https://user-images.githubusercontent.com/811806/211543666-80816f9c-2f58-45ad-bfb9-c0444d9419c1.png) | ![image](https://user-images.githubusercontent.com/811806/211543772-43fdc552-ce4a-4784-a0bd-73e3d6e15ecf.png) |

[docs]: remove duplicate sentence

---

src/types.ts

fix: proper docs link in jsdoc

---

package.json
pnpm-lock.yaml
tests/isVisible.spec.ts

`attachTo` can be removed when https://github.com/jsdom/jsdom/issues/3502 is fixed
With jsdom v21.1, `getComputedStyle` is cached and not updated for elements not in the DOM
so some our tests fail (because the elements are checked a first time)
We'll probably see issues in Vue projects using VTU and jsdom as well, and we can point to this PR if that happens

fix: use attachTo in failing tests with jsdom v21.1

---

package.json
pnpm-lock.yaml

This should solve the pnpm error:
```
├─┬ @vue/test-utils 2.2.8
│ └── ✕ missing peer @vue/compiler-dom@^3.0.1
```
This was brought to our attention by @shinigami92 on DIscord

chore: mark @vue/compiler-dom as optional

---

docs/guide/advanced/v-model.md

As reported by https://github.com/vuejs/test-utils/discussions/1969, the `emits` field of a component needs to be defined to properly typecheck.

docs: add emits to v-model documentation

---

docs/api/index.md
src/utils/autoUnmount.ts

I think this change for `enableAutoUnmount` type makes it easier to understand.
If ok, i can change types in this PR too )

docs: change type for unableAutoUnmount

---

docs/api/index.md

Fixes #1470
Some events, like clicking on a checkbox to change its `v-model`, will only work if the test uses `attachTo: document.body`. Otherwise, the `change` event will not be triggered, and the `v-model` value does not change.

docs: mentions attachTo in trigger documentation

---

docs/.vitepress/config.ts
docs/guide/advanced/ssr.md
package.json
pnpm-lock.yaml
rollup.config.ts
src/createInstance.ts
src/index.ts
src/renderToString.ts
test-dts/renderToString.d-test.ts
tests/renderToString.spec.ts

It is now possible to use `renderToString` to test the SSR rendering of a component.
To do so, use `renderToString(MyComponent)`.
`renderToString` returns a `Promise<string>` with the HTML rendered.
```ts
it('returns correct html with pre-fetched data on server', async () => {
const Component = defineComponent({
template: '<div>{{ text }}</div>',
setup() {
const text = ref<string | null>(null)
onServerPrefetch(async () => {
text.value = await fakeFetch('onServerPrefetch')
})
return { text }
}
})
const contents = await renderToString(Component)
expect(contents).toBe('<div>onServerPrefetch</div>')
})
```

feat: add renderToString function

---

src/mount.ts
src/vnodeTransformers/stubComponentsTransformer.ts
tests/components/RecursiveComponent.vue
tests/shallowMount.spec.ts

Fixes #1162 
I'm not really happy with the wording, because there is a lot of double negation. However, the code does the job

fix: Stub instance of the same component

---

docs/guide/extending-vtu/plugins.md
src/domWrapper.ts
src/wrapperFactory.ts
tests/exists.spec.ts

fixes #1984 
Rationale: Rather than overriding `exists` on DomWrapper, I elected to instead return a wrapper error from DomWrapper's ctor if the provided element is nullish. 
This allows the ctor of DomWrapper to be changed to allow `null | undefined` without having to propagate `null | undefined` downwards into `BaseWrapper.constructor`, `BaseWrapper.wrapperElement`, `BaseWrapper.element`, and `WrapperLike.element`, a change that would be significantly breaking and cause consumers of test-utils to have to add non-null assertions all over the place.
This also simplifies some other uses cases, like for example the one I changed in plugins.md.

fix: return wrapper error from DOMWrapper ctor if element is nullish

---

src/types.ts

At the moment it suggests to use `data` instead of `propsData` but that does not work and just seems straight up wrong. It seems obvious to me it should be suggesting to use `props` instead since that actually works..

Fix propsData deprecation suggestion

---

src/index.ts
src/mount.ts

export ComponentMountingOptions to resolve type definetions in testing script by user.
demo like bllow
```typescript
import { mount， ComponentMountingOptions } from '@vue/test-utils';
import Tree from '../src/Tree.vue'; // Tree is a component.
type MountingOptionsTree = ComponentMountingOptions<typeof Tree>;  // Note this line
function getTreeWrap(
props: MountingOptionsTree['props'] = {},
options: MountingOptionsTree = {}
) {
return mount(Tree, {
props: {
count: 1,
...props,
},
attachTo: 'body',
...options,
})
}
```

export ComponentMountingOptions to resolve type definetions in testing script by user

---

src/domWrapper.ts
tests/setValue.spec.ts

Adds missing trigger of `input` event when calling `setValue` on the following elements:
- `input[type=checkbox]`
- `input[type=radio]`
- `select`
- `option`
fix #2014 
I've created a playground to test the event trigger of the browser, to match the same behavior:
https://sfc.vuejs.org/#eNrNVM1u2zAMfhVClyRAY6M5Bk6wYdgLbMdpB1dhYrW2JEiy28Dwu5eSnDRN/wIUBeqLSX4f+ZG2qJ79NCbrWmRLVjhhpfHg0LdmzZVsjLYeerBYCi87hAG2VjcwIf6EK66EVs5DrXewOpKm//7PDohUpvVA4HQGqzVVImpmWldNJwkSZV3jZjKD4ZAiqlLt8PWcETtNKvLUNLVLjsfG1KVH8gCKjezWAMEkp1rEYHh+VSjubvTDiOQjxH2RmvJ7gyvOxIHG4EcEKBbfIZBaiaxgcJYk86AZWhnlX4r/KTdSf6BsI+ciWVBlc5LyFeUuGOov1ij82VRkuhi/+PPFHG281Aq6sm4D4Zqw6yJP0TdZC2Itzlh0NKL8syHSeXh3DGja2ktT42fmORb5FoP97lDFPT0/eMk9rA108622pDolut1fgZzRCsc8Bss73IeRT//Vk1p4+h5iHgy0mCPj2F2wn6/nCJ2E2RVLd868KU1267SiW6mPjY6A42wJMRJi …

fix(setValue): trigger input event for checkbox, radio and select

---

src/createInstance.ts
src/mount.ts
tests/__snapshots__/shallowMount.spec.ts.snap
tests/renderToString.spec.ts

`renderToString` unit test now runs in `node` environment and not `jsdom`.
The `attachTo` option has no usage on `renderToString`. Should we print a warning, when it is used?
Fix #2020

fix(renderToString): Remove document usage on SSR render

---

docs/api/index.md
src/renderToString.ts
src/types.ts
test-dts/renderToString.d-test.ts
tests/renderToString.spec.ts

Prints a warning when using `attachTo` option on `renderToString`.
I had to use `attachTo?: never` because the options are typed with `RenderMountingOptions<any> & Record<string, any>` (See https://github.com/vuejs/test-utils/pull/1079)
Related to #2023

fix(renderToString): Remove attachTo from options and print warning on usage

---

package.json
pnpm-lock.yaml

We used `optionalDependencies` in #1958 but I think the proper way is to use `peerDependenciesMeta`. This fixes the current issue where pnpm installs compiler-dom and server-renderer in v3.2.47, despite v3.3.1 being available.

fix: properly declare optional peer deps

---

src/vnodeTransformers/stubComponentsTransformer.ts
tests/features/async-components.spec.ts
tests/features/plugins.spec.ts
tests/mountingOptions/global.stubs.spec.ts

This MR introduces an ability to find async component stubs by definition of **underlying** component, not just by wrapper itself
It also mimics `@vue/test-utils@1.x` behavior (well, kinda) - `@vue/test-utils@1.x` was unable to stub async components due to limitations in our patch approach, so "finding" always worked cause there were no stubs

fix: allow finding async component stubs by definition

---

docs/.vitepress/config.ts
docs/guide/faq/index.md

Added a FAQ section to the docs and some info about the `Vue warn: Failed setting prop`
Relates:
#2035
#1995
Makes obsolete: #2067

docs: add FAQ for "Vue warn: Failed setting prop"

---

src/createInstance.ts
src/vnodeTransformers/stubComponentsTransformer.ts
src/vnodeTransformers/util.ts
tests/components/RecursiveComponent.vue
tests/shallowMount.spec.ts

On re-render of the root component it used the cached stub from the recursive usage. Now I don't extract from cache for root components. I had another approach which adds another return value `cache: boolean`, but this was more difficult more code than just adding the condition.
fix #2039

fix(stub): re-render of recursive component using wrong cached stub

---

.github/ISSUE_TEMPLATE/bug_report.md

As we do receive quite a few issues about types, I think it would be nice to use repros that come with vue-tsc (and vitest of course) out of the box.
Note that this link can point to any of the snapshots listed here https://github.com/vuejs/create-vue-templates/tree/main but I suppose a minimal one by default is better

chore: use a stackblitz repro with create-vue for issue template

---

.github/ISSUE_TEMPLATE/config.yml

Adds two links when creating a issue. One to discussions and another to the test-utils v1 repo
Example on vitest repo: https://github.com/vitest-dev/vitest/issues/new/choose

chore: show links on create of github issue

---

src/vnodeTransformers/stubComponentsTransformer.ts
tests/mountingOptions/global.stubs.spec.ts

fixes #2072 
* fix: allow to use Teleport, Transition and TransitionGroup in PascalCase in stubs

fix: allow to use Teleport, Transition and TransitionGroup in PascalCase in stubs

---

.github/workflows/ci.yml

The generated lockfile was no longer compatible, so pnpm was not using it on CI.

chore: update pnpm version on ci

---

docs/api/index.md
docs/guide/faq/index.md

Closes https://github.com/vuejs/test-utils/issues/2074

docs: note `mount`'s dependence on system time

---

netlify.toml
package.json

This is especially useful for netlify which rely on corepack to use the proper pnpm version. Corepack uses the `packageManager` field in the pakage.json file to determine which version is used.

chore: specify pnpm v8 as package manager

---

package.json
pnpm-lock.yaml

The `processSlot` function needs `compiler-dom` so the dependency should not be marked as optional. Fixes #2107

chore: compiler-dom as required dependency

---

.github/renovate.json5
package.json
pnpm-lock.yaml
src/baseWrapper.ts

The PR introducing a new option to _not_ inline custom elements has been merged and released, allowing us to use the new version of js-beautify without introducing a breaking change.
See https://github.com/vuejs/test-utils/pull/1834 for context

chore(deps): update dependency js-beautify to v1.14.9

---

src/config.ts
src/createInstance.ts

typescript-eslint v6 don't want them, but prettier adds them.

chore: exception for no-extra-semi lint rule

---

vitest.config.ts

This gets rid of the warning we currently have when running `pnpm test`:
```
Vitest  "deps.inline" is deprecated. If you rely on vite-node directly, use "server.deps.inline" instead. Otherwise, consider using "deps.optimizer.web.include"
```

chore: use server.deps.inline for vitest config

---

docs/api/index.md

I found what appears to be a spelling error in `docs/api/index.md`.
In French, Ex**e**mple is correct, but in English, Ex**a**mple would be a more appropriate spelling.

docs: fix spell Exemple to Example

---

docs/api/index.md

I found code in the documentation that appears to omit the async keyword.

docs: Fix omission of async keywords.

---

src/utils.ts
tests/setData.spec.ts

Currently when calling `setData` on a wrapper it will not retain methods on any constructed objects passed in. These methods reside in the prototype which the current logic do not persist across. These changes will ensure that any prototype properties / methods are copied over to the proxied data object.
fixes https://github.com/vuejs/test-utils/issues/1851

Fixing prototype methods being discarded when using `setData`

---

docs/migration/index.md

Adds a comparison table of functions with v1. It has been taken from the previous table of the README.md https://github.com/vuejs/test-utils/commit/11b34745e8e66fc747881dfb1ce94cef537c455e
Preview: https://deploy-preview-2175--vue-test-utils-docs.netlify.app/migration/#Comparison-with-v1 
close #2147

docs: comparison of functions with v1

---

docs/guide/index.md

WebdriverIO has a browser testrunner allowing to run component tests on real browser revisions and not just browser engines. We added docs on how to use `@vue/test-utils` and wonder if it makes sense to add WebdriverIO to the list of supporting frameworks.

Add WebdriverIO to list of supporting frameworks

---

.github/workflows/ci.yml

node v16 is now EOL, and v20 is the active one.
See https://github.com/nodejs/release#release-schedule

ci: add node v20 and drop node v16

---

src/vnodeTransformers/stubComponentsTransformer.ts
tests/mountingOptions/global.stubs.spec.ts

At the moment, `@vue/test-utils` doesn't allow custom `<transition>` stubs. For example, setting:
```js
config.stubs.transition = {template: '<div />'};
```
...will still just render the default `@vue/test-utils` stub:
```html
<transition-stub appear="false" persisted="false" css="true">
```
The motivation for this change is that if you're using the `@vue/compat` migration build, these default stubs throw up the following warning:
```
Error: (deprecation ATTR_FALSE_VALUE) Attribute "persisted" with v-bind value `false` will render persisted="false" instead of removing it in Vue 3. To remove the attribute, use `null` or `undefined` instead. If the usage is intended, you can disable the compat behavior and suppress this warning with:
configureCompat({ ATTR_FALSE_VALUE: false })
Details: …
```

feat: allow custom `<transition>` stubs

---

docs/guide/advanced/slots.md

There is a type in a code example in the slots documentation.
Here's the fix 😉

docs: fix typo in code example

---

src/mount.ts
src/vueWrapper.ts
test-dts/wrapper.d-test.ts
tests/getComponent.spec.ts
tests/props.spec.ts

At the moment, `mount()` offers [strong typing][1] of props, but this strong typing is lost when dealing with the `VueWrapper` through either the `props()` or `setProps()` methods.
This change strengthens the typing of these methods to help raise compile-time errors when trying to get or set incorrect props.
[1]: https://github.com/vuejs/test-utils/blob/11b34745e8e66fc747881dfb1ce94cef537c455e/src/types.ts#L44

fix: stricter props types

---

.github/renovate.json5
package.json
pnpm-lock.yaml

The `dependencies` packages are pinned to a fixed version and updated through renovate. However without a release it still uses the old versions on projects. I've changed them to use a version range and changed renovate config to don't pin the depdencies

chore(deps): Set range for dependencies

---

src/baseWrapper.ts
tests/text.spec.ts

This change fixes wrapper.text to handle suspense components with multiple elements in a slot.
When suspense component had multiple elements in a slot, wrapper.text returned empty.

fix: wrapper.text method

---

vitest.config.ts

Tests are roughly twice faster with this option.
Before:
```
Duration  7.58s (transform 859ms, setup 441ms, collect 8.55s, tests 2.61s, environment 15.28s, prepare 3.19s)
```
After:
```
Duration  3.06s (transform 1.03s, setup 344ms, collect 7.36s, tests 2.08s, environment 1.58s, prepare 4.25s)
```

chore: use experimentalVmThreads to run unit tests

---

src/utils/find.ts

This fixes the test failure in https://github.com/vuejs/test-utils/pull/2233
Vue 3.3.8 added a new type in the `VNodeChildAtom` union type: https://github.com/vuejs/core/commit/405f34587a63a5f1e3d147b9848219ea98acc22d#diff-9b2ba253038f7b71dbbbcb545e028d2d51d27d88b041b918c9eb102a83fef189R117 causing incompatiblity with the type defined in this repository.
By using types exported from the `vue` package instead of defining our own, we can avoid similar breakges in the future.
`VNodeChild` type has been available since 3.0.0-beta.1.

fix(types): use `VNodeChild` type from `vue` to avoid breakage

---

docs/migration/index.md

Documentation about the removal of the `createWrapper()` function and how it can be replaced with `new DOMWrapper()`.

docs: Add removal of createWrapper

---

src/mount.ts
test-dts/mount.d-test.ts
test-dts/shallowMount.d-test.ts

Just getting this ready for the latest https://github.com/vuejs/core caused by https://github.com/vuejs/core/pull/7338

preparing for Vue 3.3.9 

---

package.json

at the moment the subpath import condition for `import` loads a 'bundler' version which expects a browser environment (it references `document`). But node running in a native ESM context will also resolve this condition.
To fix simply, we can inject a `node` condition in front of it which will force node to use the CJS version.
Longer term, I would recommend _also_ producing an ESM version that does not rely on a browser context.

fix: always load cjs bundle in node environment

---

vitest.config.ts

It changed in vitest v1 https://vitest.dev/guide/migration.html#pools-are-standardized-4172

fix: experimentalVmThreads is now pool=vmThreads

---

src/baseWrapper.ts
tests/props.spec.ts

It seems that using the vm from `currentComponent.subTree.component.proxy` is more accurate in that case instead of `currentComponent.proxy`
fix #2300

fix(findComponent): Use correct vm for stubbed component with selector

---

docs/fr/guide/advanced/vue-router.md
docs/guide/advanced/vue-router.md

It seems like the highlighted parts of the code in the [Testing Vue Router](https://test-utils.vuejs.org/guide/advanced/vue-router.html#Using-a-Real-Router) page may have slightly move upwards.
This will fix all the highlights in the code blocks of this section to match what is said in the documentation.

fix(vue-router.md): update highlights when mocking real router

---

docs/api/index.md
docs/fr/api/index.md
src/types.ts
tests/mountingOptions/attachTo.spec.ts

fix #2194
Changed the type of attachTo in MountingOptions from HTMLElement to Element.
Do I need to update documentation?

fix: update attachTo type in MountingOptions interface

---

docs/api/index.md
docs/fr/api/index.md

There is a typo in the anchor tag that links from the isVisible documentation to the attachTo documentation.

docs(api): fix typo in attachTo anchor tag within isVisible

---

docs/guide/advanced/v-model.md

missing a equal sign in [Testing v-model](https://test-utils.vuejs.org/guide/advanced/v-model.html#A-Simple-Example):
```js
const App {
components: {
Editor
},
}
```
change to:
```js
const App = {
components: {
Editor
},
}
```

docs: fix missing equal sign

---

src/vnodeTransformers/stubComponentsTransformer.ts
tests/mountingOptions/global.components.spec.ts

Fixes #2395
We now explicitely call the default slot with an empty object to ensure that `<ComponentWithSlot v-slot="{ count }">` won't throw when tested with `renderStubDefaultSlot`.

fix: renderStubDefaultSlot with scoped slots

---

docs/api/index.md
docs/fr/api/index.md

The example of the [shallow](https://test-utils.vuejs.org/api/#shallow) API misses the suffix "stub" when making assertions. 
`Component.spec.js`
```js
import { mount } from '@vue/test-utils'
import Component from './Component.vue'
test('shallow', () => {
const wrapper = mount(Component, { shallow: true })
expect(wrapper.html()).toEqual(
`<a-component-stub></a-component-stub><another-component></another-component>`
)
}
```
should change to:
```js
import { mount } from '@vue/test-utils'
import Component from './Component.vue'
test('shallow', () => {
const wrapper = mount(Component, { shallow: true })
expect(wrapper.html()).toEqual(
`<a-component-stub></a-component-stub><another-component-stub></another-component-stub>`
)
}
```

docs(api): fix missing chars

---

docs/fr/guide/advanced/teleport.md
docs/guide/advanced/teleport.md
tests/docs-examples/teleport.spec.ts

closes #2402
Updated `tests/docs-examples/teleport.spec.ts`; `tests/features/teleport.spec.ts` is still using `outerHTML` though.

docs: use innerHTML in teleport cleanup

---

src/vueWrapper.ts
test-dts/wrapper.d-test.ts

I used to contribute and it seems I had this laying around for years now without committing. Small improvement for getting better type inference.

feat: Added dynamic return for element getter

---

src/vnodeTransformers/stubComponentsTransformer.ts
tests/props.spec.ts

Fixes #2411
We can "trick" the warning introduced in Vue v3.4.22 (See https://github.com/vuejs/core/commit/7ccd453dd004076cad49ec9f56cd5fe97b7b6ed8) by using an array of strings instead of a string (as the new check allows functions and arrays, but not strings). This does not affect the rendering of the stub, and still displays `[Function]`, so it should not impact the existing tests.

fix(stubs): avoid warning on normalized props with Vue v3.4.22

---

.github/workflows/ci.yml

This is the default behavior when the version is not specified, allowing to have the same version without updating it in two places.

chore: use the packageManager field from package.json in github action

---

docs/api/index.md

Update index.md to fix typo and clarify `get` vs `find` behavior differences
Saw that there was a typo while reading the docs myself and thought I should contribute. Change is minor.

Update index.md to fix typo and clarify `get` vs `find` behavior

---

.github/workflows/ci.yml

Node v22 is currently failing with segfault, so let's disable it temporarily

ci: remove node v22 build

---

docs/api/index.md

- Fixed typos (missing period)
-  Clarified behavior of `findComponent` vs `getComponent`.
- Added notes about `get` and when to use it in the `find` section so that if users only check the `find` section of the docs they will see when to use `find` vs `get` (as opposed to before when it was only specified in the `get` section of the docs.

Update index.md to fix typos and clarify behaviors

---

src/createInstance.ts

Fixes #2483
The introduction of `idPrefix` in Vue's `AppConfig` object triggers a TS error that we can't really get rid of (see #2483 for a more detailled explanation).

chore: ignore TS error in config object

---

src/index.ts

Being `Stubs` an existing type on test-utils, and having to import declarations on test files, this PR helps to remove boilerplate to always declare something along the lines of:
```typescript
import { RouterLinkStub } from '@vue/test-utils';
interface SetupProps {
props: MyComponentProps;
stubs: Record<string, boolean | typeof RouterLInkStub>;
}
function setup({ props = {}, stubs = {} }: SetupProps = {}) {
render(MyComponent, {
global: { stubs },
props,
});
}
test('something', () => {
setup({ stubs: { 'router-link': RouterLinkStub, MyModal: true } });
expect(screen.getByText('foo')).toBeDefined();
});
```
or setting up manually Component or DIrective types from vue itself:
```typescript
import { RouterLinkStub } from '@vue/test-utils';
import { Component, Directive } from 'vue'; …
```

chore(index): exposing Stubs type for declaration files

---

docs/api/index.md
docs/fr/api/index.md

This PR fixes an issue where the code incorrectly treated wrapper.find('div') as a boolean value.
**Changes Made**
Replaced expect(wrapper.find('div')).toBe(true) with expect(wrapper.find('div').exists()).toBe(true)

fixed incorrect checkbox value check

---

package.json

This PR resolves #2462 
Should also resolve #234 even though a bit late now ;-)
Simply inverts `browser` and `require` exports definition inside `package.json` so that `Webpack`-powered projects running tests in a browser context (and not in Node) take the correct build while bundling.  
See #2462 for detailed discussions.

Fix/issue 2462 - Vue is not defined in projects using Webpack and in-browser testing solutions

---

package.json

- no peer dependencies causes @vue/test-utils to import stuff from the wrong Vue version in monorepos with multiple Vue versions
- too specific peer dependencies causes dependant projects not to be updated or find a valid Vue version so the range has been widened
closes 2507

fix: re-add peer dependencies but with wider range (#2507)

---

docs/guide/extending-vtu/plugins.md

just followed the implementation of [Data Test ID Plugin section guide ](https://test-utils.vuejs.org/guide/extending-vtu/plugins.html#Data-Test-ID-Plugin)and notice that actually the DOMWrapper was not being imported.

import missing DOMWrapper on Implementation of Data Test ID Plugin

---

docs/migration/index.md

The `ref` syntax is indeed not working, see https://gitlab.com/groups/gitlab-org/-/epics/14954, so I figured this could be part of the migration guide from v1 to v2.

chore: add migration step for deprecated ref syntax in findAllComponents

---

README.md

Updated the README.md file to reflect the new documentation path, as the `packages` directory does not exist, changing it from `packages/docs` to `docs`.

chore: update documentation file path

---

tests/components/PropWithSymbol.vue

This modification aims to resolve warnings encountered when running `docs:dev` :
We are now using Vue 3.5+, so `withDefaults` is [unnecessary](https://vuejs.org/api/sfc-script-setup.html#defineprops-defineemits).

fix: resolve warnings in docs:dev

---

docs/fr/guide/essentials/conditional-rendering.md
docs/fr/guide/essentials/forms.md
docs/guide/advanced/reusability-composition.md
docs/guide/essentials/conditional-rendering.md
docs/guide/essentials/forms.md
docs/installation/index.md
src/types.ts

Correct anchor hash links and fix typos in documentation
- VitePress uses titles for anchor links, so if titles are modified, the corresponding anchor hashes need to be updated accordingly. (e.g., `/api/#wrapper-methods` in French should be `/api/#Methodes-de-Wrapper`)
- fix typos: `dont => don't`

fix(docs): correct anchor hash links and fix typo

---

docs/.vitepress/theme/custom.css
docs/.vitepress/theme/index.mts

This is just a embellishment of personal opinion and can be closed directly if it is not adopted.
I would also like to add a code block to show the installation commands, but that would be a long theme customization, so I can try to implement it if you like.

docs: perf site home

---

docs/zh/guide/essentials/conditional-rendering.md

Review the Chinese translation of `essentials/conditional-rendering.md`
#2561

docs(zh-cn): enhance `conditional-rendering.md`

---

docs/zh/guide/advanced/async-suspense.md

docs(zh-cn): review async-suspense.md

---

docs/zh/guide/faq/index.md

- 修改了文档中关于 Vitest 模拟日期和计时器的说明，强调在调用 vi.setSystemTime 后挂载组件的重要性
- 更新了相关警告的描述，使其更加清晰
- 修正了文档中的链接格式和部分翻译，提高了可读性
- https://github.com/vuejs/test-utils/issues/2561#issuecomment-2565101581

docs(zh): 更新 Vitest 模拟日期和计时器的说明

---

docs/zh/guide/advanced/slots.md

docs(zh-cn): guide/advanced/slots.md

---

docs/zh/guide/index.md
docs/zh/index.md
docs/zh/installation/index.md

- `index.md`
- `guide/index.md`
- `installation/index.md`
#2561

docs(zh): review index

---

docs/api/index.md
docs/fr/api/index.md
docs/zh/api/index.md
src/baseWrapper.ts
src/interfaces/wrapperLike.ts
src/types.ts
src/utils.ts
test-dts/findComponent.d-test.ts

This PR changes the signature of `findComponent`, `findComponents`, `getComponent` to accept `FunctionalComponent<any>` as the selector.
Resolves #2594.

fix: accept FunctionalComponent<any> as selector

---

docs/guide/extending-vtu/plugins.md

There may be a better replacement, but at a minimum this brings attention to the broken link :)

Removes broken link from plugins.md

---

docs/zh/guide/advanced/component-instance.md
docs/zh/guide/advanced/reusability-composition.md
docs/zh/guide/advanced/transitions.md

- `docs/zh/guide/advanced/transitions.md`
- `docs/zh/guide/advanced/component-instance.md`
- `docs/zh/guide/advanced/reusability-composition.md`
#2561

docs(zh): review transitions, component-instance, and reusability-composition

---

docs/zh/guide/advanced/ssr.md
docs/zh/guide/advanced/stubs-shallow-mount.md
docs/zh/guide/advanced/teleport.md
docs/zh/guide/advanced/vue-router.md

- `docs/zh/guide/advanced/vue-router`
- `docs/zh/guide/advanced/teleport`
- `docs/zh/guide/advanced/ssr`
- `docs/zh/guide/advanced/stubs-shallow-mount`
https://github.com/vuejs/test-utils/issues/2561

docs(zh): review all the rest advanced guide

---

src/baseWrapper.ts
src/domWrapper.ts
src/vueWrapper.ts
src/wrapperFactory.ts
tests/element.spec.ts

Fix for https://github.com/vuejs/test-utils/issues/2568
This change adds a new optional parameter to the DOMWrapper constructor so information about its structure can be later used to produce correct `text()` and `html()` assertions.

fix: text() misses content for array functional component

---

vitest.config.ts

In the hope to get rid of the segfaults on ci

ci: use "pool: threads" instead of vmThreads

---

tests/trigger.spec.ts

Removes the warning:
```
stderr | tests/trigger.spec.ts > trigger > errors > throws error if options contains a target value
Promise returned by `expect(actual).rejects.toThrowError(expected)` was not awaited. Vitest currently auto-awaits hanging assertions at the end of the test, but this will cause the test to fail in Vitest 3. Please remember to await the assertion.
```

fix: use await in test

---

docs/fr/guide/essentials/a-crash-course.md
docs/fr/guide/essentials/conditional-rendering.md
docs/fr/guide/essentials/easy-to-test.md
docs/fr/guide/essentials/event-handling.md
docs/fr/guide/essentials/forms.md
docs/fr/guide/essentials/passing-data.md
docs/guide/essentials/a-crash-course.md
docs/guide/essentials/conditional-rendering.md
docs/guide/essentials/easy-to-test.md
docs/guide/essentials/event-handling.md
docs/guide/essentials/forms.md
docs/guide/essentials/passing-data.md
docs/zh/guide/essentials/a-crash-course.md
docs/zh/guide/essentials/conditional-rendering.md
docs/zh/guide/essentials/easy-to-test.md
docs/zh/guide/essentials/event-handling.md
docs/zh/guide/essentials/forms.md
docs/zh/guide/essentials/passing-data.md

Related to [#2642](https://github.com/vuejs/test-utils/issues/2642)

docs: update Essentials section to setup (composition api)

---

src/createInstance.ts
src/vueWrapper.ts
tests/setData.spec.ts

This PR adds support for `setData()` and `shallowMount({initialData: ...})` for components defined using the `<script setup>` syntax. 
To my surprise this isn't supported yet, yet it seems like an important tool, especially when refactoring components from the Options API to the Composition API.
E.g. the following test would fail:
```vue [ScriptSetup.vue]
<script setup lang="ts">
import { ref } from 'vue'
const count = ref(0)
const inc = () => { count.value++ }
</script>
<template>
<button @click="inc()">{{ count }}</button>
</template>
```
```ts
it('updates data on a component using <script setup>', async () => {
const wrapper = shallowMount(ScriptSetup)
await wrapper.setData({ count: 20 })
expect(wrapper.html()).toContain('20')
})
```
I've added a few tests to the existing setData …

Implement setData()/shallowMount with initialData for components using the Composition API / <script setup>

---

src/mount.ts
tests/mount.spec.ts

Fix #2690 
Regist a `onUnmount` to remove the wapper when append the wapper `div` to target DOM.

fix: remove wrapper div when unmount
