src/stubs.ts, tests/mountingOptions/stubs.global.spec.ts
=> feat: handle array syntax for stubs

.github/workflows/ci.yml, jest.config.js, package.json, setup.js
fix #68 
Do testing with the built files
Currently only doing tests for `cjs`, more can be added easily
=> feat: run test using build file

src/mount.ts, tests/mountingOptions/attachTo.spec.ts
Remove attaching the element to the document.body and also fix the `attachTo` element
=> fix: remove mounting to document.body and fix attachTo

package.json, src/mount.ts, tests/features/plugins.spec.ts, yarn.lock
Also silent expected `console.error` messages so that the test output is a bit cleaner.
=> Bump Vue-related deps

src/vue-wrapper.ts
This is a tiny PR in a serie of several ones to improve the typings across the codebase.
In the end, the goal is to enable `strict` compilation. But as there are several TS errors when enabled, I'll open focused PRs to fix them.
This PR does not change the behavior or the public API, just fixes some incoherences and catches potential errors.
=> chore(vue-wrapper): proper typings

package.json, src/index.ts, src/utils/flushPromises.ts, tests/features/async-components.spec.ts, tests/features/suspense.spec.ts, yarn.lock
=> feat: add flush promises

tests/lifecycle.spec.ts
lifecycle shuld be expect 'onMountFn'
=> test:lifecycle shuld be expect 'onMountFn'

src/mount.ts, src/types.ts, src/utils.ts, src/vueWrapper.ts, tests/emit.spec.ts
See some strats to support this eventually https://github.com/vuejs/vue-test-utils-next/issues/158. I am not exactly sure how to implement what is suggested here yet, so for now I think it's good to have a warning.
=> chore: add warning about emitted on functional components

src/types.ts, test-dts/mount.d-test.ts
=> fix(mount): mount should accept a partial config

README.md, src/utils.ts, src/vueWrapper.ts, tests/setData.spec.ts
Closes #228 
I've set the PR as a draft mainly because:
– I want to check Vue 3 does not allow adding arbitrary keys to `data` (https://github.com/vuejs/vue-test-utils-next/pull/230/files#diff-8922ff7832dd4405c3d942de5802a81c4426196af69c67af28dce19eb125b179R62)
– I'd appreciate help checking typings for `mergeDeep` 😇
=> Add setData

docs/.vitepress/config.js, docs/guide/essentials/easy-to-test.md
Comes from https://github.com/vuejs/vue-test-utils-next-docs/pull/52
=> docs: Add "Write components that are easy to test" page

src/domWrapper.ts, src/utils.ts, src/vueWrapper.ts, tests/text.spec.ts
=> fix: return empty string for text() on comments

src/stubs.ts, tests/components/ComponentWithChildren.vue, tests/components/ScriptSetupWithChildren.vue, tests/shallowMount.spec.ts
=> fix: shallowMount failed for script setup components

docs/guide/essentials/forms.md
=> docx：update forms.md  complexFrom example

docs/api/index.md
resolves #305
We need to finish docs soon, it's just a few hours of work. Let's do it.
=> docs: add docs on global config

src/config.ts, src/createDomEvent.ts, src/domWrapper.ts, src/emit.ts, src/mount.ts, src/stubs.ts, src/types.ts, src/utils.ts, src/utils/compileSlots.ts, src/utils/find.ts, src/utils/isElementVisible.ts, src/utils/matchName.ts, src/vueWrapper.ts, tests/config.spec.ts, tests/emit.spec.ts, tests/features/async-components.spec.ts, tests/functionalComponents.spec.ts, tests/isVisible.spec.ts, tests/lifecycle.spec.ts, tests/mountingOptions/attachTo.spec.ts, tests/mountingOptions/data.spec.ts, tests/mountingOptions/global.plugins.spec.ts, tests/mountingOptions/mocks.spec.ts, tests/mountingOptions/slots.spec.ts, tests/mountingOptions/stubs.global.spec.ts, tests/setData.spec.ts, tests/setProps.spec.ts, tests/trigger.spec.ts, tsconfig.json, types/testing.d.ts
linked #369 
This PR introduces the ts strict option
There were places where I roughly guessed the type...
There are more non-null assertion `!` and `any` type is in there then one would hope for, but it's a start.
=> Turned on ts strict option

tests/classes.spec.ts
This PR is for issue https://github.com/vuejs/vue-test-utils-next/issues/419 .
This PR is a remake of https://github.com/vuejs/vue-test-utils-next/pull/420 .
=> test: add a test case for error wrapper

LICENSE
=> chore: add LICENSE file (fix #441)

docs/guide/advanced/vue-router.md
Add missing async in test function.
=> docs: add missing async clause

package.json, yarn.lock
Should resolve this issue: https://github.com/vuejs/vue-test-utils-next/issues/245
=> Add  @vue/compiler-dom dep

docs/guide/essentials/conditional-rendering.md
I think `?` was mistyped, right?
=> chore: fix `?` to `.`

jest.config.js, rollup.config.js, src/utils/compileSlots.ts, types/global.d.ts
closes https://github.com/vuejs/vue-test-utils-next/issues/549
=> fix: use prefix identifiers for cjs build

babel.config.js, jest.config.js, package.json, tests/features/with-tsx.spec.tsx, tsconfig.json, yarn.lock
Good to have TSX to make sure everything works as expected. It does!
=> chore: add tsx

src/mount.ts, src/utils.ts
Let's bring a tiny bit of type-safety here!
=> chore: improve typings of isComponent helpers

docs/api/index.md, docs/guide/advanced/slots.md, src/mount.ts, src/types.ts, tests/mountingOptions/slots.spec.ts
Pretty self-describing :)
Recover functionality which was available in v1 :)
=> feat: support passing component with template to slots

tests/docs-examples/Signup.vue
This rewrites the teleport example to use TS.
It allows to then reactivate Volar and check all our Vue templates are fine.
=> chore: migrate example to TS

docs/guide/extending-vtu/plugins.md
Link is going to 404
Added a change to direct it to the correct page.
=> docs: update url

docs/migration/index.md
Closes #787
Wrong name for heading
Update docs to use correct name
=> docs: update name

docs/guide/advanced/vuex.md
While reading the new docs on testing Vuex I noticed and corrected a few minor typos on the page.
=> Update vuex.md to correct a few minor typos

docs/guide/advanced/vuex.md, tests/features/vuex.spec.ts
Hello, I tried to document the approach for testing components that use the useStore-helper function with and without Typescript. Most information are taken from https://github.com/vuejs/vue-test-utils-next/issues/407 and https://github.com/vuejs/vue-test-utils-next/issues/457). 
Cheers
=> Added explanation for testing useStore/compositionAPI

docs/guide/extending-vtu/community-learning.md
Shameless plug to link my ebook and online course in the learning resources, as they have a large section about testing (and hundreds of unit tests examples) using VTU 🤗
=> docs: add learning resource 'Become a Ninja with Vue 3'

src/domWrapper.ts
Fix for issue #936 
Created issue, then realized that fix is quite simple.
=> fix: domWrapper.d.ts imports

src/index.ts
Export the createWrapperError
Fixes https://github.com/vuejs/vue-test-utils-next/issues/923
=> feat: export createWrapperError

docs/guide/essentials/passing-data.md
Passing Data to Components section including unnecessary Axios import.
=> docs: removed unnecessary axios import.

docs/guide/advanced/vuex.md
the docs link for Vuex 4 : https://next.vuex.vuejs.org/
=> docs: correct link for Vuex 4

docs/guide/advanced/slots.md
The content is wrong, when I run the test it will fail.
Best Wishes.
=> Capitalize the first letter

src/interfaces/wrapperLike.ts
the problem was described here:
https://github.com/vuejs/vue-test-utils-next/issues/936#issuecomment-1000939410
=> fix: add relative imports in wrapperLike interface

src/stubs.ts
This PR will use the setup function for stubs instead of the render function with compatibility mode. Also some refactoring so transition and teleport stubs don't use separate function
=> chore: Use setup instead of compat render for stubs

docs/guide/advanced/vue-router.md
=> docs: fixed a typo in vue-router.md

package.json
=> chore: remove @vue/compiler-dom dependency

docs/guide/advanced/teleport.md
=> Fix a syntax error

docs/guide/advanced/vue-router.md
As described in the following issue (https://github.com/vuejs/test-utils/issues/1315) I felt the documentation regarding vue-router was lacking a bit, therefore I created a PR to improve the docs. Let me know if anything should be changed.
All the best!
resolves #1315
=> Update vue router docs

docs/guide/advanced/async-suspense.md, docs/guide/advanced/http-requests.md
Fixes #1360
And makes all axios spies consistent
=> docs: fix http examples

src/utils/flushPromises.ts
I think due credit is deserved here to original repo
=> chore: give credit to original flushPromises lib

package.json
Update `homepage` and `repository` in `package.json`. The one shown on npmjs is VTU v1: https://www.npmjs.com/package/@vue/test-utils
=> chore: update package.json docs

src/utils/getRootNodes.ts, tests/features/suspense.spec.ts
=> fix(find): find element inside suspense with multi root elements

tests/trigger.spec.ts
Test around #886
https://github.com/vuejs/test-utils/issues/886
=> chore: add test

docs/guide/advanced/vue-router.md
This is a one line change to an example in the `docs/guide/advanced/vue-router.md` file.
It's from [Issue 1632](https://github.com/vuejs/test-utils/issues/1632).
I'm more than happy to make any requested changes 😎
=> Documentation Update (Issue 1632)

src/utils.ts, tests/setData.spec.ts
=> fix: keep Date objects on setData

README.md
Noticed when working on another PR
Avoid this if maintainers do not intend to update README for now
=> chore: Update README since package manager was changed from yarn to npnm

.github/ISSUE_TEMPLATE/bug_report.md
Add version of to issue template to inform users about different repos for v1 and v2
=> chore: Add version info to bug report template

tests/components/ScriptSetup.vue, tests/components/ScriptSetup_Expose.vue, tests/expose.spec.ts
=> chore: Extend expose tests with not used function

src/stubs.ts
The current one does not compile with TS v4.8 changes
=> chore: improve type for stub cache

docs/guide/advanced/vue-router.md
This is a one line change to an example in the `docs/guide/advanced/vue-router.md` file.
It's from https://github.com/vuejs/test-utils/issues/1894.
=> Documentation Update (Issue 1894)

package.json, pnpm-lock.yaml
=> fix: add vue-component-type-helpers to the dependencies

src/emit.ts, src/utils.ts
=> feat: respect devtools definition

docs/migration/index.md
Closes (again) https://github.com/vuejs/test-utils/issues/2147.
I went with a super simple table, like the other ones at the bottom of https://test-utils.vuejs.org/migration/#Comparison-with-v1
=> docs: add mention of enableAutoDestroy replacement

docs/fr/guide/essentials/passing-data.md, docs/guide/essentials/passing-data.md
Adding missing data property in export default [Passing Data to Components
](https://test-utils.vuejs.org/guide/essentials/passing-data.html#Using-props-to-set-a-minimum-length)
=> docs: fix missing data at passing data section essentials guide

package.json, pnpm-lock.yaml, src/vnodeTransformers/stubComponentsTransformer.ts
This should unblock Renovate #2461
=> chore(deps): update dependency typescript to v5.5.3

package.json, pnpm-lock.yaml, src/utils.ts
=> chore(deps): update dependency prettier to v3.3.3

docs/fr/installation/index.md, docs/installation/index.md, docs/zh/installation/index.md
=> docs: support vitepress code-group

docs/zh/guide/essentials/event-handling.md
=> docs(zh-cn): review event-handing.md

docs/zh/guide/essentials/passing-data.md
=> docs(zh-cn): review passing-data.md

docs/zh/guide/essentials/forms.md
=> docs(zh-cn): review forms

docs/zh/guide/advanced/v-model.md, docs/zh/guide/advanced/vuex.md
- `docs/zh/guide/advanced/v-model.md`
- `docs/zh/guide/advanced/vuex.md`
#2561
=> docs(zh): review v-model and vuex

docs/guide/advanced/transitions.md
Greetings! I've just found a typo in Docs. So, I decided to fix it.
=> Fix a typo in transitions.md
